== Preface

Having been favoured with the perusal of the manuscripts and letters of Ruth Follows,
and believing that a selection from them would be worthy of preservation,
the editor has ventured upon the present undertaking;
and although it is upwards of twenty years since the decease of this our dear friend,
and therefore many of her remarks may not be so forcible as regards
the particular circumstances which occasioned them;
yet, being written under lively feelings, and in themselves truly valuable,
they are evidently calculated to promote the cause of spiritual religion.

Her memory is precious to many who knew her;
and a desire has often been expressed that something of her life
and religious experience should be published for more general benefit.
In offering the present memoir of our deceased friend,
it is also apprehended to be in accordance with her own desire,
that an evidence should remain of the sufficiency of Divine grace in her own mind,
and a testimony of her travail and solicitude for the welfare of others.

It has been the care of the editor to preserve her remarks, as much as might be,
in her own words or manner of expression, as being upon the whole,
the best adapted to convey instruction to the reader.

Her situation as to outward circumstances, was a humble one;
yet her example of devotedness to the service of her Divine Master was very conspicuous;
and in her beloved husband she found a true helper,
and one ever ready to promote her religious views.

As a mark of the esteem she was held in by her friends,
the following notice of her is extracted from the
testimony of the Monthly Meeting of Hardshaw East,
respecting Martha Routh:--"`That in the year 1775,
in company with that valuable minister of the Gospel, Ruth Follows,
she visited the meetings of Friends in some of the northern counties and Scotland.`"
And Martha Routh, in the early part of her own memoirs, remarks,
"`I often visited my dear and much tried friend, Ruth Follows,
and sometimes accompanied her to neighbouring meetings; her company was useful,
encouraging and edifying.`"

In the extracts from her letters, it is also hoped much instruction will be found.
They manifest a tender solicitude,
and great Christian care for the welfare of her own family,
which she continued to cherish while engaged from home on religious service.

Liverpool, Fourth month 1st, 1829.
