== Chapter III

Her visit to Friends in Ireland, and to the Yearly Meeting in London.

On the 22nd of eighth month, 1761, I parted with my dear children,
having some time before acquainted my friends with
my concern to visit the meetings in Ireland,
and they having unity therewith gave me a certificate.
My dear husband and Joseph Evatt accompanied me to Uttoxeter,
where Anne White from Coventry met me, she having the same concern.
We lodged at John Shipley`'s--and here I parted with my dear husband,
he going home with Joseph Evatt.
We next lodged at Joshua Toft`'s at Haregate;
from there to Warrington and so to Liverpool, and were at their fifth-day meeting.

On the 28th we embarked for Dublin, and were at sea three days and three nights,
in which time we had a sore tempest, and were among a very disagreeable crew;
but by Divine Providence we were wonderfully preserved, and landing safe on the 31st,
proceeded to the house of our worthy friend, Samuel Judd.

The 1st of ninth month we were at the meeting in Dublin, which though silent,
was solid and satisfactory.
We were also at the meetings on sixth and first-days,
where we laboured more in silence than in words;
being sensible that there is something among them
which at times obstructs and hinders the ministry.
May we and all those whom the Lord is engaging to visit the churches of his people,
patiently wait and willingly suffer, until the Lord`'s power be over all;
and when he is pleased to favour his ministers with strength and zeal for his cause,
and commands us to speak to the people, then let us be faithful,
and doubtless we shall witness his power to subdue our enemies,
and behold his glory as in days past.
But oh! the sins of the people are as a thick cloud,
which at times seems to cover our assemblies and
causes the true travailers very often to mourn.
We were also at their women`'s meeting on second-day morning,
and after a painful travail as through darkness,
the Lord was pleased to arise and we were comforted.
On third-day at their meeting for worship, but not yet able to clear ourselves;
so taking leave of the dear friends with whom we quartered,
in the expectation of again visiting Dublin,
we proceeded to visit the north part of the nation.
William Grubb and David Newland accompanied us to Dundalk; from there to Rathfriland,
where we had a meeting with some who professed with us.

Our next meeting was at Moyallen--from there to Lurgan
and were at their meeting on first-day,
which was very large.
Here we parted with our two friends, who had indeed taken great care of us;
and accompanied by two kind friends from Lurgan, proceeded to Lisburn,
Newton and Hilsborough, in each of which places we had a meeting.

On the next first-day we were at a large meeting near Ballinderry,
where we had very hard labour; indeed it has been so in most places,
the people are so little concerned about religion
and so much grasping after the riches of this life.
We lodged at John Murray`'s, near Brome Hedge--on second-day rode to Antrim,
lodged at an inn, and held a meeting the next day:
there are several who profess with us in this place,
but few who are worthy to be called by our name.
From Antrim to Ballycane, Grange, Ballinacree and Coleraine; also to Morgan Wilson`'s,
near Toberhead; then to Dungannon, Charlemont, Moyallen,
and to the Quarterly Meeting at Ballinderry;
being accompanied by James Christy from Moyallen.
We were at the meeting of ministers and elders, which I hope not to forget:
the meeting for worship was large, and after it the meetings for discipline were held.
On first-day at the meeting for worship,
many of us were favoured with the presence of Him who has promised
that "`where two or three are gathered together in his name,
there will he be in the "`midst of them;`" wherein we greatly rejoiced,
and took a solemn farewell of each other.
We then returned with our dear friend to Moyallen,
and on second-day morning took leave of his family,
being much broken into tears but intermixed with joy,
in the feeling whereof we still live together, though far separated outwardly.

At Armagh we parted with my friend and father in the truth, James Christy,
he returning home and we proceeding to Castlesheen, where we held a meeting.
Then to Coothill, Oldcastle Moate and Ballimurry, at which places we had meetings.
At Moate we lodged at James Clibborn`'s, whose wife was granddaughter to Robert Barclay.
Next to Tullamore and Edenderry; and from there to Joshua Wilson`'s, near Rathangan;
had a meeting at each place; so to Samuel Neale`'s,
uncle to our worthy friend of the same name, who is an acceptable minister.

+++[+++Her concern for the spiritual welfare of her dear friends at home continued unabated,
as appears by the following letter:]

To +++_______+++

Castle Donnington, Fifth month Sd, 1761.

"`Endeared friend, brother and companion in tribulation, for so it seems to me you are,
for which I have been thankful.
What strength has it given me when I found that I was at times
brought into your remembrance with other of my dear friends,
whom with yourself I do dearly salute,
humbly craving that we may ever remain in this holy fellowship,
wherein the saints in light rejoice.
For I may tell you that at the reading of yours I did rejoice,
although I was in tribulation, yet I hope in some degree of patience;
but my trials since my return have been more than I can express;
under all which for some time it seemed hard for me to submit.
Oh, this preparation! this time of purging!
Who indeed can abide the day of his coming, or who can stand when he appears,
who is as a refiner`'s fire?--but so it must be with the sons of Zion,
that they may offer unto the Lord an offering in righteousness.`"

We came to Dublin on the 28th, to our old worthy friend Samuel Judd`'s:
at this time many Friends were here from several parts of the nation,
it being both their province and Half-year`'s meetings;
during which we had the help of our friends Samuel Neale,
Thomas Greer and several others, unto whom I am nearly united in Gospel fellowship.

From Dublin we were accompanied by William Taylor to Ashton, Wicklow and Ballimurry,
to Joseph Pirn`'s. We then proceeded to Bailycane,
and were at meeting there on first-day, which I think held four hours.
On second-day we had a meeting at Askin, in the house of Henry Errats;
then we proceeded to Ballinclay, Coolatore, Randalsmills and Cooladine,
at which places we had meetings; and at Enniscorthy on first-day,
it being their Monthly Meeting; but, how painful was it to me!
After meeting we dined at Isaac Bell`'s,
and then accompanied our ancient friend Joseph Williams to his house at Dansmills;
from there to Wexford, and had a meeting to satisfaction,
although there are very few who profess with us in that place,
and those few not in the possession of the Truth, which I believe,
is one cause that our friends have suffered so much here;
the people of the town are in great darkness, but they behaved better than usual,
and I had much peace in being there.
From this place we went to Joseph Poole`'s near Forrest,
and had the company of Samuel Chambers;
from these Friends we parted in much love and proceeded to Ross with Samuel Elly,
who came to meet us; we lodged at his house and had a meeting on fifth-day;
and the weather being very wet we remained until seventh-day.
Indeed, I believe this delay was very agreeable both to us and to our worthy friend,
who had a few weeks before been parted from a good wife,
and with other circumstances was in so mournful a situation,
that our company seemed very acceptable to him.

From Ross we went to Waterford, lodged at Joshua Jacob`'s,
were at their meetings on first-day, and in the evening visited Thomas Wiley who was ill;
a comfortable season it was.
Next to Clonmel, and lodged at Joseph Grubb`'s; then to Cashell and Kilconner,
at which places we had meetings.
We then proceeded on our way to Cork, but the journey being long we lodged at an inn.
On seventh-day we got to our dear friend Samuel Neale`'s;
we attended their meetings on first-day,
which to me were times of deep travail in silence.
From Cork we went to Youghall, where we had a meeting and returned;
then to Bandon and had an evening meeting.
Our dear friend Sarah Neale and two others accompanied us,
and we all returned to Cork in order to attend the Quarterly Meeting;
the sittings of which were measurably favoured with the Divine presence;
yet there remained a great weight upon my mind until third-day,
when I was enabled to discharge my duty so as to obtain
that peace which it is our great interest to labour for.
O that all those who minister would wait the right
time and always move in their proper order,
then we should again shine among the nations.

We had several good opportunities among our friends, and left Cork on fourth-day:
visited a family at Mallow and the next day got to Limerick;
attended their meetings on sixth and first-days,
and had some profitable opportunities in a few families with James Tomey,
who was a help to us.
From Limerick we went to Tormevan, from there to Roscreagh,
had a meeting and dined at John Pim`'s. Next to Burris in Ossory,
lodged at William Morris`'s, had an opportunity in the family,
then proceeded to Joshua Thompson`'s near Ballinakili, and had a meeting the next day;
then proceeded to Carlow, the province meeting for Leinster being held there.
We attended the meeting for ministers and elders;
and on the 19th of twelfth month that for worship;
after which followed those for discipline.
In these meetings many were engaged to travail very deeply;
that on first-day was very large,
wherein we were strengthened and refreshed in the love of our God,
who is still pleased to comedown and dwell among his people,
and is helping those who put their trust in him.
We had here an opportunity of seeing many Friends
from the several counties which we had visited,
and having had renewed cause to rejoice together, in true love we again parted.

From Carlow we proceeded to Castletown, then to Kilconner, lodged at Samuel Watson`'s,
and had a meeting on third-day; from there to Robert Lecky`'s,
and on fourth-day had a meeting at Newtown.
We had been favoured with the company of Richard Shackleton, and at Newtown his wife,
father, and several other Friends met us, in whose company we proceeded to Ballitore,
and lodged at Abraham Shackleton`'s. Oh! the sweet harmony which,
is found among those families who dwell in true love.
Our next meeting was at Athy, on the 25th of twelfth month, and a satisfactory one it was.
We then proceeded, accompanied by Abraham Shackleton and Ephraim Boake, to Maryborough;
from there to James Pim`'s near Mountrath, and attended meeting on first-day.

On second-day to James Hutchinson`'s, at Knockballymaher,
and had a meeting both large and satisfactory.
Then to Kilconnermore and Birr, where we had meetings;
and on seventh-day to Thomas Strangman`'s at Mountmellick,
and attended their meeting on the next day.
While here I was in much trouble, yea, afflicted almost beyond measure, which indeed,
has been my portion in many places in this poor nation.
Oh! had those who account themselves ambassadors
of Christ kept properly under the holy anointing,
and never dared to move without it,
our assemblies would not have been so full of confusion,
nor our solemn feasts so often marred.
It is such things which cause so many spots in our feasts of charity;
and under a sense thereof the true ministers mourn: yet let me thankfully acknowledge,
the Lord has not forsaken his people, but those who truly fear his name,
at times behold his glory.

+++[+++The following letter written from Edenderry,
expresses her concern for her beloved family:]

Edenderry, Tenth month 24th, 1761.

My dear husband,

By these you may know that we enjoy health and peace, two great blessings:
and believing you were thoughtful about me, I was desirous to write;
yet have hope that you, my dear, will live by faith, for so we must endeavour,
as it is and will be our lot to be much parted.
Let us therefore learn submission to the will of our God,
for nothing short thereof can obtain his peace.

I have hope that as I am in the way of my duty I shall be preserved,
although we travel through considerable difficulties both from within and without.
We have been through the North,
among a people that fear not God as they ought--yet blessed be our Lord,
we have felt his power and love to be extended even to these poor rebellious creatures.

I am often with you in spirit, looking as into your meetings,
where you have none to rely upon but the Lord.
Wait therefore for his appearance, and he will arise for your help;
for did we enough seek him, I am sure it would be better with us as a people.
Let us not forget those who have been of peculiar service,
as indeed has our well beloved and worthy friend Thomas Cornwall,
of whose removal I have heard.
Oh!
I have mourned and sorrow has filled my heart, until tears gave some relief.
He has been as a father to me and many others--He helped
to rebuild the walls of our Zion which had been broken down;
and he has been of great service many ways.
Therefore let a just regard be paid to his memory.
And I desire that those who are left behind,
who have known and do still talk of the goodness of God, may not play the coward,
but when under right influence be sure to do their duty, and not start aside:
for behold the ways of Zion mourn, because so few come to her solemn feasts.

We next attended the Monthly Meeting at Edenderry,
whore the Truth was declared.--We dined with our worthy friend Thomas Bewley;
then went to Isaac Jackson`'s, where to our great comfort, we met with Thomas Wiley,
who had been very ill for a long time.
At this place we also met with Richard Shackleton and his wife,
and were favoured with their company at Rathangan, at the week-day meeting.
From there to Joshua Wilson`'s, where we lodged; visited Thomas Pim`'s family,
and on the 7th of first month parted with our dear friends.
Abraham Shackleton had been with us about two weeks.
Joseph Inman, Isaac Jackson and Samuel Watson accompanied us to Baltiboys;
we lodged at Samuel Peasley`'s, had a meeting on sixth-day,
visited the families who professed with us, and under a sense of Divine love,
parted with our dear friends and proceeded to Dublin,
where we arrived on the 9th of first month, 1762.
Here we stayed expecting to sail in a vessel bound for Liverpool, but it not being ready,
we found close engagement and great exercise of mind in this city.
Sometimes I had an opportunity to plead with the people;
but examples of silence are needed, such was I very often,
and desire that it may be more practised there.
While we were thus waiting in the hope of shortly leaving the country,
a concern fell upon Anne White to visit families;
and when I found that she was engaged in the city,
I saw that it was my duty to return into the country;
and finding that sensible honest Friends had unity with me in my concern,
it was a great help to me.
My exercise was great, more than I can express;
but having learned that except we bear the cross we must not wear the crown,
I submitted to the yoke of Christ, which by obedience becomes more easy.

Accompanied by Thomas Wiley and his brother John,
I left Dublin on the 2nd of second month,
and that night lodged at Samuel Neale`'s near Rathgannon;
the next day got to James Pim`'s, and they were I believe, very glad to see us.
We attended their meeting at Mountrath on fifth-day to satisfaction,
and I was made thankful that I had given up to attend these meetings.

To Her Husband.

Portarlington, Second month 6th, 1762.

My last, written in Dublin a week since, I hope you have received:
it gives you an account of our waiting for a vessel,
having then a hope that we should have been at liberty as soon as it was loaded.
My dear companion has since found a concern upon her mind to visit families in Dublin;
but I did not feel any engagement of the kind; yet when she had begun I then saw my way.
I did not hastily make it known,
but the Lord who has been my helper is still near and has made way for me,
even to admiration.
Some sensible Friends visited me, querying of me,
if it would not be best for me to turn into the country?
I confessed that it was my concern and found it was my duty to give up to it,
but the thought of your expectation of seeing me soon,
made the exercise exceedingly heavy: yet I am thankful that the way is opened for me,
for how affecting it would have been to come home and had no peace until I returned.
But He in whom we trust hears our cry,
and if we be faithful will deliver us from all those things which at times
are allowed to try us deeply--but we must submit to his will.

Do not be uneasy about me for I am in careful hands;
and if it be the will of God that I should here end my labours,
you well know I cannot be better employed; and as you are my fellow-helper,
you not only suffer with me,
but will also rejoice with me in that joy that is unspeakable and full of glory.
O that we may
'`run with patience the race that is set before us,`'
still looking unto Him who is the Author,
and I trust will be the '`Finisher of our faith:`' yea,
He that was our '`Morning Star will be our Evening Song.`' Yet we must exercise patience,
which I believe, is our individual care and concern,
and that hope will doubtless be added of which we have no need to be ashamed.
O! how great is the harvest, and how few are the faithful labourers!
Yet, blessed be the Lord! he has not left himself without a witness,
neither is his glory departed from our Israel.
No, no: for we can at times say, '`how goodly are your tents, O Jacob,
and your tabernacles, Israel:`'--'`the Lord our God is with us,
and the shout of a King is among us.`'

I now feel my spirit near you,
and also near to my beloved children.--In the pure and undefiled
love of the Gospel I once more salute you all,
and bid you farewell.

On first-day we attended the Monthly Meeting at Mountmellick,
which was large and a time of hard labour to those who had a right sense of feeling;
but the Lord whom we served was with us, and I left the place in peace.

After being at Kilconner, Waterford and Clonmel,
I came to Limerick and attended the province meeting on first and second-days;
some of us stayed the meeting on third-day also.
The whole were exceedingly painful; and what made it more so,
some who are accounted teachers do not mind to keep their places,
but are for feeding the people, yea,
they do feed them with that which is not rightly prepared, and so increase the disorder.
I believe that it would be better if the people were to know a true fast.
On fifth-day we reached Cork, where I lodged at my worthy friend Samuel Neale`'s,
and attended their meetings on fifth and first-days.
We had some satisfaction in this visit,
being favoured with the renewings of the love of our God,
wherein we were nearly united to some and hope that
we shall ever remain in this holy fellowship,
wherein the saints in light rejoice.

Our next meeting was at Kilconner, on fourth-day; and that evening went to Cashel.
Robert Fennel accompanied us, stayed with us at the inn,
and on the morrow went with us many miles.
It was very difficult travelling on account of the snow,
but after a long and hard journey,
we arrived at Mountrath on sixth-day morning the 12th of third month,
and attended the select meeting, where We felt the extensions of Divine regard,
and were thereby engaged to labour among them.

On seventh-day we were at the province meeting; on first-day at a very large meeting,
wherein, after a time of deep travail in silence,
we were once more renewed and strengthened in our spirits,
and enabled by the power of the Most High, to worship and praise his ever excellent name.
After being at several other places,
we arrived at our dear friend Thomas Greer`'s at Dungannon, on the 25th of third month.
On sixth-day the select meeting was held at Grange, near Charlemont,
where on the two following days, was the Quarterly Meeting for the province of Ulster.
These meetings were times of suffering--yea, to those who were rightly concerned,
of deep baptism; but after a long time of travail,
the Lord our God was pleased to arise for our help,
and in and by the might of his power were his servants
once more enabled to testify of his name,
and the meeting ended well.

Here I parted with my dear friends Thomas Wiley and J. Russell,
who had accompanied me I believe, more than a hundred miles.
On third-day went to Lurgan,
from there to Lisburn and attended their meeting on fifth-day.
On first-day I was at a meeting at Ballinderry which was large,
and after a time of deep travail in silence,
we were made sensible that the love of God was extended,
under the influence whereof the people were afresh pleaded with, and called unto.
On third-day had a meeting at Newtown to some satisfaction--on fifth-day one at Hillsborough,
and then returned to Lisburn.
On first-day the 11th of fourth month, several Friends accompanied me to Lurgan meeting,
where there are many who profess with us; but,
alas! they are departed from the Rock of their strength,
and a dull heavy meeting it was for the most part.

From this place I went with James Christy, his sons and daughter Sarah, to Moyallen,
and remained there until fifth-day morning,
when I was favoured with his company to Banbridge,
where Phebe Watson and I got a carriage to convey us to Dublin;
so I parted with my kind friend at whose house I had been many times during this journey,
and was well satisfied with some conversation we had while travelling these few miles;
his son John went with us to Dublin, where we safely arrived on the 16th of fourth month.
Finding my engagement to be at the Half-year`'s Meeting continued,
I duly attended the sittings thereof, and in some had true satisfaction,
being confirmed in my mind that I was still in the way of my duty to God.
The company of Samuel Spavold and several others, was truly acceptable;
and although a time of painful labour and much suffering,
yet were we satisfied and thankful,
being united in spirit and favoured to experience
the love of God and the extension of his power,
so that the meeting ended well.
Near the conclusion I took a final farewell of my dear friends,
with and among whom I had so long been engaged.

I now waited for a vessel and also for company,
several Friends intending for the Yearly Meeting at London;
and as it had for some time appeared to me that I must be there also,
I waited until the 15th of fifth month,
and that evening went on board a vessel bound for Liverpool: we had a good passage,
arrived about five o`'clock the next evening and lodged at Richard
Hillary`'s. On second-day some of our company went to Chester,
to hire horses to carry us to London.
On third-day we left Liverpool and attended Warrington Monthly Meeting,
which was large and satisfactory.
On fourth-day got to Leek and stayed their meeting,
where the Lord was again pleased to favour us with his presence,
and to renew our spiritual strength.
Here several of our company parted; but Abraham Shacklelon,
Joseph Grubb and Thomas Wiley continued with me,
and accompanied me to my own home at Castle Donnington; we arrived on sixth-day night,
where we were gladly received by my dear husband and children,
and finding them well was indeed a great satisfaction to me and cause of thankfulness;
yea, we rejoiced together in humility and in the fear of our God,
for whose cause we had been thus separated,
by whose power we had been preserved through many deep trials,
and now brought to meet again in pure peace.
Oh! that we may still live to praise his holy name, who is forever worthy!
Having acquainted my husband and friends of my intention of going to London,
and ascertained their unity therewith,
I again sat out accompanied by my dear friends from Ireland,
and reached London on the 27th of fifth month, 1762.

I stayed in and about London more than two weeks, attending meetings.
On first-day the 13th of sixth month,
was at the meeting in Gracechurch street in the morning,
and at Devonshire-house in the afternoon,
at both of which I was enabled to bear testimony in the power which God gives;
and by so doing I obtained great peace.
It was also satisfactory to many F`'riends,
who were glad that I now could depart from this great
city with an easy mind and a cheerful countenance,
for they had not seen me much in that situation during the time of my stay.
Oh! the deep travail of soul that I often experienced! and desirous I am that such a
travail were more frequently witnessed by those who would be called the "`sent of God.`"
But, alas! too many there are who do not keep near enough to the holy anointing,
but are too much led by the desires of the people, whose ears are after words.
Surely if I be rightly sensible, I have sorrowfully felt this to be the case,
and while such things prevail among us the true seed will suffer;
but we still have cause to be thankful,
knowing that the Lord has not forsaken his people,
but is raising "`judges as at the first and counsellors as at the beginning.`"
A number there are who truly wait for wisdom and by it divide the word aright,
and when these speak they speak as the oracles of God;`"
these are they who do administer grace to the hearers;
and that the number of these may increase is the desire and prayer of my soul.

On the 15th of sixth month, I left London on third-day morning about two o`'clock,
and got safely the same evening to Leicester,
and on the 16th attended their Monthly Meeting at Hinckley;
from there to Leicester Quarterly Meeting on the 18th,
in which those who were rightly concerned,
were made sensible that the power of God was with us,
by which some were enabled to worship him in spirit and in truth.

I now returned home with my husband, but contrary to my hopes, met with fresh exercise;
but I desire that I may learn patience,
and by passing through many and great tribulations may know
my robes to be made white in the blood of the Lamb,
that so having suffered with him we may also reign with him in his glory.
