== Chapter VI

[.chapter-synopsis]
* Her visit to the Northern Counties and Scotland, in company with her friend Martha Winter

Having for some time had a concern to visit meetings in the northern counties and Scotland,
and having the concurrence of my friends and a certificate for the purpose,
my dear husband accompanied me to Nottingham, on the 21st of fifth month, 1775;
on the 22nd we parted.
My dear friend Martha Winter, who had the like concern,
accompanied me on the 23rd to Breack, where we had encouragement to go forward.
We then had meetings at Furnace, Matlock and Chesterfield; on the 27th,
our worthy friend William Coning,
with many other Friends from Sheffield met us at Dronfield,
and after a trying meeting we accompanied them to the former place,
and were at their meeting on first-day to our satisfaction.

On the day following we had a meeting at Woodhouse, very laborious;
yet we had the reward of peace,
and being true helpmeets and fellow-labourers in the Gospel,
we were a comfort to each other.
On the 30th had a meeting at Burton near Barnsley; and in the evening went to High Flats,
having the company of John Swanwick from Sheffield to this place.
Were at their meeting on the 31st, which was very large and satisfactory,
although we had very close work, as indeed has been our lot hitherto;
yet when we witness the power of God to be over all,
there is cause for thanksgiving and praise.
On the 1st of sixth month had a large and satisfactory meeting at Wakefield;
then to Gildersome, to a large and painful meeting.
Then to Leeds and stayed over their meeting on first-day, and very painful was our labour,
but by a faithful discharge of duty we obtained peace.
At Rawdon we again had close work, but were comforted with God`'s good presence,
whereby the right-minded were strengthened.
On the 6th went to Undercliffe, to John Hustler`'s,
and the next day were at meeting at Bradford to satisfaction.
On the 8th to Brighouse and afterwards to Halifax,
where we had a laborious time:--at this meeting we
had the company of our friend Phebe Marshall.

On the 10th to Todmorden, and lodged at Samuel Fielden`'s, where I was taken very ill,
yet was enabled to be at meeting and labour hard among a scattered people:
we were favoured with the company of George Howarth, a very aged Friend,
who had an acceptable time in supplication, which was a help to us.
From this place we went to Marsden, and on second-day were at meeting at Trawdon,
which though small, was a time of favour.
Next day had a meeting at Marsden, where many people were assembled,
but we were both silent; we had, however,
a comfortable opportunity with several Friends at our quarters, and parted in true love.
At Crawshaw-booth meeting on the 14th, through deep travail and honest labour,
we obtained peace.
Here we met James Brandwood from Edgeworth, and accompanied him to his house.
On the 15th we had a very satisfactory meeting at Edgeworth; the next day at Oldham,
where, among a poor few, our strength was greatly renewed,
and we encouraged to hold on our way.

At this place Jonathan Flounders of Manchester, met us,
and with him and James Brandwood we were several nights at John Routh`'s in that town.
On the 18th were at four meetings;
in the two for worship had some degree of satisfaction,
being favoured with the help of Him who remains to be the true helper of his people.
My old companion and fellow-labourer, Sarah Taylor,
also bore a living testimony to the Truth.
And oh! says my soul, that all we who at times have to make mention of the great name,
may dwell near to it and know our abiding to be in it,
that so our worldly concerns may not have too much room in our minds,
and thereby dim that glory and bring a cloud over that brightness,
in which we at times have appeared in the congregations of God`'s people.
On second-day afternoon we went to Warrington, and were at three meetings on the 20th;
first, the Select Meeting, where was very close labour, yet a time of favour;
the meeting for worship was in the beginning overshadowed with good,
but being hurt by an unskillful hand, did not end so well;
there was a large number of Friends, being their Monthly Meeting,
and in the women`'s meeting our friend Sarah Taylor was favoured in supplication,
even for us who had a long journey before us.

On the 21st went to Langtree, and Henry Binns from Preston, having come there to meet us,
we went with him; on the 22nd had a meeting at Preston, which, though small,
yet that power that is not limited to time, place or number,
was indeed wonderfully made manifest;
and we came away with the rich reward of pure peace.
At Lancaster we lodged at our worthy friend William Dillworth`'s,
and attended their meetings on first-day,
the 25th. In the afternoon was a funeral attended by very many people, which was a solid,
edifying season; and although I had passed through deep suffering,
and being poorly as to health, was very low, yet we came away rejoicing.
Accompanied by several Friends from Lancaster, we came to Kendal,
having an invitation to the funeral of two Friends, an elderly woman and her son,
a widower, interred together.

On the 29th we went to Preston Patrick, accompanied by many Friends from Kendal,
and were favoured with a good meeting; after which we dined at George Crosfield`'s,
and spent most of the afternoon with these worthy Friends.
We returned to Kendal to their Monthly Meeting on the 30th,
and were not easy to leave until after first-day,
at which meetings we were helped to labour, and by our obedience witnessed peace.
In the evening many Friends were together at our friend Thomas Crewdson`'s,
and I believe it was an edifying season, wherein we were again comforted,
and parted in true love.
On the 3rd of seventh month, we came to Grayrigg, where we had a meeting,
a searching time indeed, but seemed to end to satisfaction.
On the 4th we went to Moreland, and on the 5th to Penrith,
and were at their Monthly Meeting; there were a large number gathered at this place,
and it was a time of renewed visitation to those poor souls,
who as is the case with many in other places, seem to live in forgetfulness of God.
Oh, what an alarming time it was; the trumpet was indeed blown as in Zion,
and an alarm beat as on God`'s holy mountain; would that the people be gathered.
On the 6th we went to Scotby and on the 7th had a meeting,
in which the power of the Lord was manifested;
in the afternoon went to William Sutton`'s, where was an agreeable family,
and our heavenly Father was with us, so that we seemed united in his love,
and had to speak well of his name, who over all is blessed forever.
Amen.

On the 8th went to Carlisle, and were at both meetings on first-day;
it was a time of close labour among a multitude of revolters;
but through best help we were favoured to come away in peace,
and got that evening to Kirklington, and had two meetings the following day at Solport,
to some satisfaction.
On the 11th we came to Kelso in Scotland,
and had a meeting on the 12th. There are but few in that town who profess with us,
but other people came in, and we had a satisfactory season.
On the 14th we departed, having James Anderson for our guide through Scotland.
We got to Edinburgh the same night, and were at both their meetings on first-day.
There are few in this place who profess with us, and most of them have not the mark,
or much appearance of Friends either in dress or address;
and yet such is the regard of the Shepherd of Israel,
that he is seeking after these and affording them renewed visitations,
so that if they will not be gathered the fault is their own.
Oh! what did we suffer in this place! yet through
the help of Him who never fails his faithful children,
we were enabled to discharge our duty, and go on with some degree of peace.

On the 17th we crossed a ferry seven miles over, rode to Kelso,
and lodged at William Brown`'s, with whose family we had an opportunity in the evening.
On the 18th we travelled above forty miles to Arbroath, and next day to Montrose,
and in the afternoon to Urie; lodged at Robert Barclay`'s,
and had a meeting with several who profess with us, and I think it was a time of favour.
Oh! that it may not be forgotten, for the mercy of God was wonderfully extended.
From hence we went to Aberdeen, and had a meeting; then to Old Meldrum,
and were at their meetings on first-day, where was a large number of poor professors:
yet notwithstanding this sore revolting, the Lord was pleased to make his name known,
and we had great cause to rejoice.
This was the farthest place we visited in the North of Scotland.

On the 24th we returned to Aberdeen and Stonehaven, near Urie,
and on the 25th to Montrose; from there to Arbroath; and on the 26th,
after a long day`'s travel,
got to Joseph Brown`'s. On the 27th we again crossed the ferry,
and there being a calm we were four hours on board.
On landing we took coach for Edinburgh, and were kindly received by our friends.
In the evening came James Buck and Isaac Whitelock from Leeds,
and James Morris from Philadelphia;
they having seen my husband at Nottingham and my dear companion`'s family,
gave us a pleasing account of their welfare;
and as we inclined to sit with the Friends of this city,
we had the company of these strangers also,
and were favoured with a solemn satisfactory meeting,
whereby some of our spirits were nearly united.
In true love we took leave and got to Kelso,
to the comfortable little habitation of the kind Friend who has been so long with us,
and were kindly received by his mother and very valuable sister:
with the other three Friends we attended their meeting, which is very small indeed,
and it was a time of close exercise and deep suffering.
The 2nd of eighth month we got safe to Newcastle,
being still favoured with the company of James Anderson.
We attended their meeting on fifth-day, much to our satisfaction;
on the following day had a meeting at Shields,
and were again owned by our heavenly Father.

On first-day were at the meeting at Sunderland, where there was a large number of people,
but alas! few who live as they ought;
yet the kindness of the Lord was manifested:--at this meeting
we were favoured with the company of Mabel Wigham,
who now belongs to it.
We left Sunderland on second-day, having parted with our kind Scotch friend,
with whose company we had been so long favoured.
In the evening we got to Durham and had a meeting next day:
we had very close and painful labour, yet were so favoured with Divine good,
that I thought we could say the truth was over all.
Hence to Bishop Auckland, and had a meeting to satisfaction; then to Darlington,
and had a meeting wherein the Gospel was preached in the demonstration thereof.
In this town there are many who have the appearance of Friends, and I think are so.
From this place we were accompanied by four Friends to Northallerton,
where a small meeting is held, and with the few who attended we sat in great poverty,
yet were favoured with some degree of best help before we parted.
On first-day were at Thirsk meeting, where we had the company of Robert Proud,
who with us laboured in the ability received,
and by our obedience we still are favoured with peace.
On the 15th we were at Huby, and had a meeting with a few, but very little life appeared.

William Tuke from York met us, and we went with him to his house;
his worthy wife was then at Scarborough, labouring in her allotment,
and it was no small cross to us not to have her company;
we were at their meeting on fifth-day, where we had some satisfaction,
and should have had much more if the arising of the pure spring had not been hindered,
and rather resisted, by too much reasoning.
From York we went to Knaresborough; and had a meeting on sixth-day,
which was very much favoured with the presence of our God,
and glory was ascribed to his most worthy name.
At Settle we had a solid satisfactory meeting on first-day the 20th, in the forenoon,
but not so much so in the afternoon.
Had a meeting at Skipton on third-day, wherein we had very painful labour indeed;
from there to Garfield, and had a satisfactory meeting with a few.
At Leeds meeting on fifth-day, where many were truly comforted together.
Next day to Pontefract, where we had a time of deep suffering,
but were helped through and witnessed peace.
From there to Newell and met with our-valuable friend Mary Leaver,
being the first of our seeing her since her return from America.
She had an acceptable opportunity in testimony at a meeting then held in the house.
On third-day had a meeting at Blyth; and one at Retford on fourth-day,
when many of the town`'s people came in, to whom the Gospel was freely preached,
and sweet peace was our reward.
On fifth-day had a meeting at Kirsall; the next evening got to Nottingham,
where my husband met me;
we stayed over the forenoon meeting on first-day and reached our own home that evening,
the 3rd of ninth month.

[.offset]
+++[+++The following was written to her son:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Donnington, Eleventh month, 1775.

After long expectation we received your acceptable letter,
and were glad to hear of your safe arrival;
for many fears and doubts had arisen respecting you.

Let not little matters disturb you, but endeavour to do your best;
and if you are not able to do much for the Truth, be sure that you do nothing against it.
I beg you will labour, as you say, to get near us,
and be willing to sympathize with us in mourning for your poor brother, who indeed,
is bone of our bone and flesh of our flesh.
I am desirous also, that you may be an acceptable communicant with us,
when the cup of blessing is handed forth.
O what a favour it was, that we could rejoice together in that heart-tendering love,
and breathe in that pure Spirit by which we are adopted, and can cry, Abba, Father!
And being as we think, sorely chastised, yet herein are we encouraged,
seeing that '`whom the Lord loves he chastens.`' O that patience may be abode in,
and true resignation experienced, that so at the end of this painful pilgrimage,
'`well done,`' may be our reward.

Neglect not spiritual or temporal things.
Seek after the best company, that so an improvement may be known.
I think there are some in who endeavour to promote
the cause of Truth both by example and precept;
and as example is far better than precept, see that you become of these.
'`Study to be quiet,
and do your own business;`' and wherein you have
missed the right way let what is passed suffice,
and do so no more.

--

During the remainder of this year and part of the following,
I attended a number of meetings near home; and on the 11th of fifth month, 1776,
although suffering under many infirmities, I left home,
having a concern to attend the Yearly Meetings of London, Colchester,
Woodbridge and Norwich, in which engagement I had the concurrence of my friends,
and a certificate accordingly.
At Leicester I met Mary Leaver and Anna Coulson, they also intending for London.
We attended meetings in various places on our way.
The Yearly Meeting was attended by a large number of Friends, and many solid,
satisfactory meetings we had,
wherein we were mutually comforted in our heavenly Father`'s love,
and some did celebrate his praise.
Having stayed in London until the 5th of sixth month,
and taken leave of many in much love and near sympathy,
I accompanied several of my dear friends, among whom was Sarah Stephenson,
to Chelmsford, and had some satisfaction in being at their meetings.
I also paid a last visit to our worthy friend John Griffith.
At Colchester the meetings were attended by several public Friends,
and much labour and deep travail was witnessed--sometimes the Truth was over all,
and the Lord was magnified.

[.offset]
+++[+++From this place she wrote to her husband as follows:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Colchester, Sixth month 8th, 1776.

I gladly received yours and rejoiced at the account of your good health,
with that of your little company;
and can also inform you of my welfare and sweet peace of mind,
which you well know is only obtained by pure obedience.
I know that your heart will be comforted in reading of me in this present situation;
and I have no doubt of your good desires for me,
that by a steady and faithful perseverance I may
still have this richest of blessings in possession,
for it has been and I desire it ever may be so,
that we have rejoiced in this more than in anything in this world.

The Yearly Meeting was large and much favoured with the presence of the living God,
who is alone the crown and diadem of all our assemblies.

Oh! did the people enough endeavour to be gathered nearer to the Lord,
and thereby witness redemption from the vanities of this world,
how much more comfortable would our meetings be:
we have great cause to be thankful to the God and Father of all our mercies,
for the continuance of his gracious regard and tender visitations to the children of men.

The last meeting I was at in London was the Peel meeting,
where I comfortably sat in company with Samuel Neale and my dear Ann Byrd,
and nearly were we united in our heavenly Father`'s love,
which indeed surpasses the understanding of the natural man.

The following day with several valuable Friends I came to Chelmsford,
feeling an engagement to sit their meeting on fifth-day,
and to visit our much afflicted and truly worthy friend, John Griffith,
who seems near a comfortable close--his very dear love is to you.

On sixth-day, having seemingly taken a final farewell of this our dear friend,
we got to this place last night, and were kindly received by our worthy friends,
John Kendall and his wife.

--

From Colchester, accompanied by Sarah Stephenson and John Kendall, I went to Manningtree,
where we had a very comfortable meeting; after which I was left alone;
but my lodging being at that worthy, aged Friend, Mary Bandock`'s,
I was much pleased with her company.
From hence I went to Ipswich, and met with Mary Oxley and Elizabeth Candler,
from Norwich; and after a satisfactory meeting in this town, where my son Samuel met me,
we went in the evening to Woodbridge.
Our worthy friend Samuel Neale, accompanied by Richard Shackleton and Abraham Abell,
who had attended the Yearly Meeting in London, were also here,
and had good service in the meetings.
At Norwich also, Samuel Neale was much favoured.
In this city I stayed at my son Richard`'s many weeks; attended the burial of my grandson,
and was made helpful to them in their affliction.

During my long stay, I visited many Friends and most of the meetings in the county;
was afresh united to many in Norwich and favoured with a comfortable parting meeting,
taking leave both of Friends and my dear children in the nearest affection,
in that love that will go beyond the grave.
In my return I had a companion from near Skipton, in Yorkshire, Margaret Hartley,
who had been at Norwich, and with whom I had visited many meetings in Norfolk.
We attended about twenty meetings on our way to Nottingham,
some of which were satisfactory opportunities, and owned of our heavenly Father.
At that town my husband met me,
and after staying over first-day I took leave of my companion,
she going towards her home, and I with my husband to ours,
where we arrived safe with the reward of peace, the 16th of ninth month, 1776.

[.offset]
+++[+++The following letters were addressed to her son:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Nottingham, Tenth month, 1776.

We received yours and were glad to hear of your continued health:
through mercy we also are enjoyers of that great blessing.
Our concern for you my dear son, is very great, who like others,
are way-laid with temptations.
Your religious and pious father was so affected with the account I gave of you,
that he pressed upon me to mention it; that if possible,
our united concern may in some measure prevail, and your good desires increase,
so that every hurtful thing may be watched against and firmly withstood;
and that you may witness an increase and advancement in pure wisdom,
by which you would see the foolishness of the wisdom of this world.
I would hope that a hint to remind you will be rightly taken;
for as our care for all our children is great, so are we desirous to do our duty,
and not deprive them of any good, either spiritual or temporal.

[.signed-section-context-open]
Donnington, Second month 8th, 1777.

We received yours dated tenth month, and glad were we to hear of your good health; and,
oh! that your conduct was such as would proclaim you a Christian!
I would willingly hope, that you sometimes look back and weep,
like that people who had grievously revolted,
and therefore were captive in a strange land,
and could not sing a Hebrew song--they sat weeping by the rivers of Babylon,
yet had Zion in their remembrance.
Is this your case, my son?
Do you not sometimes think of the way of your fathers,
and of that pure spiritual worship performed by them,
when you were often made to partake with them of that spiritual food,
that bread which comes down from heaven,
whereby your poor soul was nourished?--You did taste of eternal life,
and then was that stony heart melted, and you had true feeling.
And, oh! that such times may not be quite over; nor you, by repeating sin,
harden yourself,
and thereby bring upon yourself destruction--the fault then will be your own.
You well know that you have been very often visited, and great has been,
and is our concern for you; we are very doubtful you have not had the letters we sent,
for they would have testified of our continued care,
which I now have not words to express.
As all is vain, except you take heed to the Witness,
which I believe has not quite left you, therefore to it I recommend you,
as the only sufficient help.--Wherever you are,
and into what part of the world soever you may be driven, it will find you out.
Oh! our son, did you but feel our affectionate regard,
and the many visits that our spirits pay you,
frequently flying as over the ocean to see what you are about!--And be assured,
here are many wish you well,
and would rejoice with us to see you home in an agreeable condition of mind.

--

+++[+++From the date before mentioned to the year 1782, a period of about six years,
it does not appear that she travelled with a certificate,
but was much engaged in attending general and other meetings near her own home.

In this time she wrote the following letters:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband.

[.signed-section-context-open]
London, Third month, 1777.

I gladly received your letter, and rejoiced to hear of your welfare; and through mercy,
I can now give an agreeable account of myself.
I am still greatly favoured with health,
and although I have had very deep and painful travail,
yet I can say of a truth that the Lord has been my helper, and my exceeding great reward.
Some may very likely wonder at my long stay in this city,
yet I believe there are many who can witness for me that I have waited the right time,
and now seem near leaving my dear friends in this place;
hoping to go on fourth-day to Chelmsford, to John Griffith`'s; from there to Colchester,
Woodbridge, etc.

May but my dear +++_______+++ endeavour to be a comfort to you;
and oh! that we may all know a growth in the blessed truth, that so when we meet,
we may have to rejoice in the increase of God, and in the aboundings of his goodness,
have to praise his holy name, who indeed has done great things for us;
and that he may be by us ever counted worthy, is the sincere breathing of my soul.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To A Relation.

[.signed-section-context-open]
Donnington, Eleventh month, 1778.

Were we but nearer one to the other,
how comfortable it would be to be together now and then; yours is a poor spot,
and we here are not very rich; or at least it is my case;
having now so little of the life of true religion in myself,
or feeling of the stirrings of it in others, that I seem to languish.
But well remembering the need there is for clean vessels,
and that it is the right time to wash them when they are empty,
may this be a time of refining to me, that all my dregs may be washed away,
and I fitted as a new bottle, that new wine may again be put therein;
so that my drooping spirits may be revived,
and we may rejoice in the feeling of the fresh springs thereof,
though far separated as to the outward.
This is more desirable than the increase of corn, wine or oil,
as with all outward blessings, the world cannot give peace to the soul.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Son Samuel.

[.signed-section-context-open]
Donnigton, Eighth month 27th, 1779.

Go on patiently--Is it not good for you to feel your own burden?
Consider how much greater difficulty thousands are now in, who have large families,
and very little to support them with.

I should be glad if I could say anything that would be of service to you,
but you well know that the best help is in yourself.
O look there--ask of Him who '`gives liberally and upbraids not.`' Neglect
not your chiefest duty of laying up for yourself treasure in heaven,
and there is no doubt with me,
that you will then have a comfortable share of earthly blessings.

It is worth while now and then,
to look a few years back at the situation your seemingly undone brother
was in--in whom there was little hope of such a change as we now see nor
would he ever have so far conquered without a good and strong resolution.
O that my dear children may all overcome the wicked one,
that so I may salute you as young men, who are strong,
having the word of God abiding in you.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Son.

[.signed-section-context-open]
Donnington, Tenth month 29th, 1779.

We were glad to receive yours, and to find that a sense of good and a desire after it,
still attend your mind;
and perhaps your poor body being afflicted might be a means of arresting your attention,
making you sensible of the uncertainty of this life,
and raising desires in you to be prepared for a better.
Oh! the many struggles and conflicts, with deep baptisms,
that all those have whose desires are to be devoted to God`'s service,
and wholly redeemed from every over anxious pursuit after the things of this life.
I, your poor mother, who for many years have been exercised in the work of religion,
am still sorely beset, and often in great fear lest I should become a prey to the enemy.
Since I last wrote you, I went to the circular meeting at Gloucester,
which was very large, and attended by some solid Friends and abundance of people,
who behaved well.
The overshadowing wing of Divine love was manifested,
and some living testimonies were borne to the praise of our God,
and to the honour of his name.
Did all who would be called ambassadors, keep close enough to the holy anointing,
and neither add nor diminish, how comfortable our assemblies would be.
I was favoured with sweet peace for the discharge of duty, not only there,
but at many places in my going and returning,
for which favour I beg to be truly thankful.
But now I witness a stripping, and am reduced to much poverty of spirit,
like an empty vessel set by for a season; and it is my care to be kept clean,
in order that when my great Lord sees fit to make use of me, I may be in readiness,
or if he be pleased to take me to himself, I may not be surprised.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Son +++_______+++

[.signed-section-context-open]
Shipston, First month, 1781.

I have been kindly received in most places; for which favour I am often humbly thankful.
Oh! that I might not labour in vain!--however, I have peace in discharging my duty,
and I beg to be clear of the blood of all men.

How near are my children to my soul,
and how frequently do I breathe unto God on their account,
begging of him yet to remember mercy, and not cast them off in anger,
but still own them as his children, and as a part of his inheritance.

O my son! you well know that this is the travail of my soul;
you are also sensible that we cannot do the work one for another;
therefore neglect not your day, but remember in prosperity and health,
what you vowed in your sickness, and how desirous you were to be spared a little longer:
was it not so with you?
Did not the Lord hear your cry, and grant you your petition;
and now will you not answer when he calls,
and accept of that grace that would be sufficient?

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Children.

[.signed-section-context-open]
London, Fifth month, 1782.

The hearing so good an account of the welfare of you all,
is great satisfaction and comfort to my mind; and had it been right for me to be at home,
I think I should have been glad once more to see two of my dear sons together.
I am not at my own disposal;
but under the care and direction of Him who is a Father unto us all,
and as I commit myself to Him, so do I commit to his care my dear children,
with all other concerns of this life, well knowing that we cannot provide for ourselves,
neither can we preserve ourselves.
Therefore,
as we know that it is the Lord alone who has hitherto been our best help--oh!
that I and mine may still endeavour to live in pure obedience to his Divine will;
that so our peace may flow as a river, and our righteousness as a mighty stream.
It has been so with me in this journey; and by such great favours, yea,
merciful kindnesses, have many bitter cups been sweetened.
O, my dears, feel with me, and rejoice: learn also,
to bear a part with me in my sufferings; that so we may go hand in hand,
and now and then ascend to the holy mount, where we can sing the Lord`'s praise.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Norwich, Sixth month 22nd, 1782.

Strong are my desires for you all, as for myself,
that we may abide in the Truth and witness a growth therein,
in order that a few living stones may be supporters of a holy building.
O, my dears, look to it, and remember what station you are in.
In the love of the Gospel I beseech you to take heed how you walk,
and that you so demean yourselves as to be ensamples to the flock of Christ,
and feeders of his lambs--way-marks unto all, both within and without.
We are watched, and we must watch also, even against every appearance of evil;
and not allow our own wills to prevail,
but let our dispositions be brought into true subjection,
that we may experience the truth of the lion and the lamb lying down together,
and of the weaned child playing at the hole of the asp,
and the sucking child laying its hand upon the cockatrice`'s den,
and that nothing can hurt or destroy upon God`'s holy mountain.
I had no thought of penning these things when I sat down,
but merely to give you an account of my welfare, as through mercy I am bravely,
and our children here are the same.
I had much comfort in son +++_______+++`'s company at Woodbridge,
and had a few agreeable lines from him the other day,
wherein he expresses his great satisfaction in paying you a visit,
and having seen us all to his comfort.
As he is still in a weak state, though better,
he says if it be the Divine will to remove him, his peace will be much greater,
having the favour of being reconciled to us,
by the renewings of that love which we know to be of eternal duration.
Oh! what a blessing to my dear offspring,
that they are so visited and favoured with a true sense of the Divine will.

--
