== Chapter VII

[.chapter-synopsis]
* Her second visit to Ireland

In the seventh month, 1782, I requested a certificate for going into Ireland,
which was granted; and had the company of Mary Ridgway and Jane Watson,
who were about to return to that country, after visiting most of the meetings in England.
I left home on the 13th, with my dear husband,
and proceeded to my kind friend Richard Reynolds`', of Colebrook-dale.
On the 16th, with Mary Ridgway and Jane Watson, we were at their meeting,
much to our satisfaction; on the 17th I parted with my dear husband,
which was a sore trial.
I then went with many Friends to the Monthly Meeting at Salop,
and from there back to Colebrook-dale, where I remained until first-day,
and was at the meeting at Newdale.
We afterwards proceeded to Holyhead, and on sixth-day, the 26th, sailed in a packet,
and were landed at Dunleary, on seventh-day, where we lodged.
We got safe to Dublin on first-day forenoon, and were all kindly received by our friends.
On second-day were at a funeral;
a large meeting was held on the occasion at Meath street, which was satisfactory.

On third-day, at the week-day meeting, we were again owned by our dear Lord,
and his name was praised.
On sixth-day at Sycamore-alley meeting, which was also satisfactory.
On first-day attended the meeting in Meath street in the forenoon,
and were favoured with gracious help; in the afternoon at Sycamore-alley,
where some light appeared.
On third-day we attended a marriage in Meath street, but it was a dull,
heavy and painful time.
On sixth-day we had a very satisfactory meeting;
my great Lord was pleased to enable me to bear testimony to the blessed Truth,
in the power whereof his holy name was magnified,
and the souls of his living children were comforted.
On first-day, the 11th,
in the forenoon my dear friend Mary Ridgway was much
favoured both in testimony and supplication;
the afternoon meeting was very dull; after which we went to James Forbes`',
where were many Friends, and a humbling season it was to me, and I think, to some others.
O that such favours were not so soon forgotten,
but that a right improvement might be made and good fruits brought forth,
to the praise of the Great Husbandman,
who still waits to be gracious to the children of men!

From Dublin, accompanied by a young woman named Rachel Jenkinson,
we proceeded to Rathfriland, and were at their meeting on fifth-day.
But few profess with us in that place, and still fewer have the Truth in possession;
so that those who visit them in the love of the everlasting Gospel,
have hard and dull meetings; yet a call is extended,
and when the messengers have done their duty, peace is their reward.
Several Friends from Moyallen met us, and there we went,
to our ancient friend Thomas Christy`'s. On first-day, the 18th,
we were at both the meetings at Lurgan, to some degree of satisfaction--a large number,
but the lack of weight is sorrowful.
On second-day we had a trying meeting at Moyallen,
but I was favoured with best help to discharge my duty.
On third-day to Ballyhagen; then to Lisburn, Hillsborough and Newtown.
We returned to Lisburn, and were at William Rogers`'s in the forenoon,
and at John Gough`'s in the afternoon.
On first-day, the 25th, at a large meeting at Ballinderry.
Then to Antrim, Ballymena, Grange,
Ballinacree and near Toberhead arriving on seventh-day at our friend
Thomas Greer`'s. On first-day were at a large meeting at Grange,
near Charlemount; and here parted with our kind friends James Christy and John Conran,
who had accompanied us round the lough,
and by their care and tenderness made our journey much pleasanter.
We stayed at Dungannon until fourth-day,
and were at their men and women`'s meetings at Grange;
and although the life of true religion is very low in this as in other places,
yet Divine favour was witnessed, and I was mercifully helped to discharge my duty,
and came away with peace.
Our dear friend James Christy, senior, meeting us,
we went with him to his daughter-in-law`'s, the worthy Deborah Christy,
with whom he dwells; and were at their meeting at Moyallen, on fifth-day,
much to our satisfaction.

[.offset]
+++[+++From Stranmore near Lisburn, she wrote to a friend as follows:]

[.embedded-content-document.letter]
--

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Stranmore, near Lisburn, Ninth month 7th, 1782.

We often have to lodge at very poor inns, yet being accompanied by two worthy Friends,
and greatly favoured with the smiles of our heavenly Father`'s countenance,
and having his holy help to discharge my duty in every place,
have enabled me to rejoice in suffering.
I am humbly thankful that my great Lord condescends to employ me in his service,
not only for my own improvement, but sometimes for the help of others.
Now and then we find one or two whose souls are thirsting
after God--perhaps one may be found as in a tribe,
but not always one in a family; yet what favours are still extended,
and how are the distant ones laboured with to come near,
and that those who are near would truly acknowledge his might.
Oh! how earnest are my desires that the love of Truth might more and more
abound in the hearts of those who have long made profession of it;
and that the love of the things of this perishing world did not so much prevail;
for the people having so much love for the world,
there is not room for the love of the Father to dwell richly in them.
O that all my Father`'s children were truly obedient to his law,
willing to be such as he would have them!
What a beautiful family should we be,
and how would the house of our God be adorned with clean vessels,
on whom his own image would be engraven, and holiness would be proclaimed to his name.
Now, my friend, you know my travail, labour and deep exercise is,
that I may witness an increase of those things that belong to my peace,
in which I rejoice more than in the increase of corn, wine and oil.

--

On first-day, the 8th of ninth month, were at Lurgan, at their men and women`'s meeting,
which was very large, and measurably owned by the Divine presence.
We stayed their weekday meeting;
on fifth-day were at Lisburn then returned to the
Quarterly Meeting for the province of Ulster,
which was concluded on first-day, by a very large meeting for worship.

At these meetings were Robert Valentine and his companion, John Hall;
and much labour was bestowed upon a revolting people,
among whom the Lord did manifest his power and
magnify his own name--it is still precious to a few,
and such as truly gather thereto find a place of safety.
From Lurgan we proceeded to several places, attended seventeen meetings,
and on the 15th of tenth month, with Samuel Neale and his wife,
were at a meeting at Cork, and had a satisfactory season.
Indeed, we had many favoured opportunities, both in meetings and in families;
and I think I may say, that I was owned by my great Master,
and favoured with his Divine presence in most places;
though it was often my lot to travail very deep before the spring arose: our labour, too,
is often hard, because we find few true helpers.
We left Cork on fourth-day morning; next day, the 17th, had a meeting at Garryroan,
and an affecting opportunity at Joshua Fennell`'s. To Clonmel on the 18th,
where we had a meeting, and lodged at the widow Grubb`'s. On the 19th,
rode to Waterford--were at both their meetings on first-day, also, at the Select Meeting,
and that for discipline.
On fourth and fifth-days we visited several families,
which was very satisfactory to myself, and, I believe, to my friends also.
Returning to Clonmel, we attended the Select Meeting on the 26th,
and the Quarterly Meeting on the two following days:--best help was granted us,
and several opportunities afforded, wherein some were nearly united in the one Spirit,
which is the bond of peace.

After attending the meetings of Carlow and Ballitore,
we arrived in Dublin on the 1st of the eleventh month,
in time for the Half-year`'s meeting.
It commenced the next day, and ended on the 6th, and was attended by Robert Valentine,
and many worthy Friends; but our meetings were heavy and cloudy,
though some Divine help was witnessed.
On my return to this city, I met with my dear companion, Ann Byrd,
who ought to have come over with me, but delayed, yet not finding peace at home,
came afterwards.
It seems now an acceptable time,
and we have had many remarkable opportunities among our friends here.

[.offset]
+++[+++From this city she addresses her husband and children with these lines.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband and Children.

[.signed-section-context-open]
Dublin, 1782.

I salute you all in the love of the Gospel, in which I wish you health and salvation;
and although far absent in body, I am often with you in spirit,
and sometimes you are with me in my near approaches to the throne of Divine grace.
Oh! may we ever be preserved in a holy dependance upon, and in pure obedience unto,
the Divine will! considering that these fleeting moments will soon be over.
If we patiently bear the cross, we shall undoubtedly wear the crown.
Oh! how many foretastes have I had of that endless felicity, since I came into this land.
Yea, I think I may say, that in most places where I have been,
my good and great Lord has enabled me to speak well of his name.
Although I have many, many deep plunges, I find they are times of refinement,
and when I am helped from there I can sing the song of praise.
And thankful is my soul that you are not strangers to these things,
but are sharers with me in the commonwealth of our Israel.
Be sure to hold on your way--slack not your pace--and let my dear +++_______+++
keep in remembrance the remarkable deliverances he has known,
so that he may well say, as was said formerly, '`What has the Lord wrought!`'

The kindness of Friends is great, and a very cordial reception I have had in most places,
and am afresh united to those whom I knew before.
Let my dear friends know, that they are often in my remembrance,
and that I send them an affectionate salutation in my heavenly Father`'s love,
in which I wish they may be nearly united one unto another, and that grace, mercy,
and peace may be multiplied.
This is the desire of their well-wishing friend,
and sympathizing companion with the true mourners in Zion.

--

On the 12th of eleventh month we left Dublin, got to Wicklow that evening,
and had a meeting on the 13th; at Ballahan the next day,
and in the evening got to Ballinclay,
at which place we were at the marriage of William Knott and Abigail Wright; a solid,
satisfactory meeting it was, there being also many present who did not profess with us.
From there to Joshua Smithson`'s, and had a meeting on sixth-day;
after which to Cooladine; then to Jacob Golf`'s,
and lodged there two nights:--he had a very large family,
and some comfortable opportunities we had with them.
On the 19th to Ross, and had a meeting there much to our comfort.
Our great Lord owned us in all these meetings, and employed us in his service.
But, how hard was our labour in most places! the people
being so leavened with the spirit of this world,
and so in love with its vanities, that the life of religion is lost in many.
On fourth-day we were favoured with the company of Jacob Goff and the widow Elly,
and had a meeting at Kilconner.
On sixth-day at the Select Meeting at Carlow, where were Robert Valentine, John Hall,
and John Conran; the Quarterly Meeting was held the next day,
and a very large meeting for worship on first-day,
in which the everlasting Gospel was preached;
many hearts were made to rejoice and joy in the God of our salvation.

On the 25th, we had a very dull meeting at Castle Dermot.
We then proceeded to the house of our kind friend, Richard Shackleton,
who with his wife are of great use in our Society.
This was a very agreeable place for poor travellers to rest at; and I being very unwell,
we stayed above a week.
On fifth-day, the 28th, were at their meeting,
where through much exercise and deep travail,
we were at length favoured with best help to do our duty.

On first-day attended their meetings, but were silent in both.
On second-day went to Joshua Pim`'s, near Rathangan, and had a meeting next day;
and on fifth-day one at Timahoe; from there to Ann Wiley`'s, at New Park,
and Joseph Inman`'s, at Ballibritain.
On first-day we attended the meetings at Edenderry; then came back to Joseph Inman`'s,
and were favoured with an opportunity before we left, which I wish we may not forget.
On the 10th we attended the Monthly Meeting at Edenderry;
on the 12th had a meeting at Mountmellick;
and on seventh-day attended the Monthly Meeting at Montrath, which was large, and,
I believe, satisfactory to some, who had not quite lost the life of religion.
Although there is not much of it to be felt,
being almost in a state of stagnation through the prevalence of evil,
yet we had many opportunities to plead with the backsliders,
both in meetings and in families, and their states were very closely spoken to.

We next proceeded to a meeting at Knockballymaher, and our chaise being broken,
we stayed at this place several days.
On the 21st we lodged at the widow Walpole`'s,
who had six sons and as many daughters--a large and hopeful family.
On the 22nd were at Ballinakill, where, as at many other places,
we were favoured with best help.
The next day we reached Clonmel, lodged at Samuel Grubb`'s,
and were twice at their meeting on fifth-day, which was satisfactory.
We visited the father and mother of Joseph Sparrow, who was lost about a year before,
on his way for England, the vessel being wrecked and many lost;
he was going with an intention of marriage to a Friend of Minehead.
The visit we paid to the afflicted parents, with whom we had near sympathy,
although exceedingly humbling,
yet was greatly favoured with the living and powerful presence of our God,
who alone can and does sweeten every bitter cup, that he sees fit to hand for our good;
and we had to believe, that this great trial would be of use to many of those concerned,
if entire resignation be experienced.

[.offset]
+++[+++Here she again addresses her beloved husband and children.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Waterford, First month 2nd, 1783.

Perhaps we may leave here next week.--How long we
may stay at Clonmel on our return we cannot say,
the Friends there being desirous of our joining them in a family visit;
but if our great Lord does not direct us, their desires will not avail;
if we should be so engaged it may be well.
After leaving there, it is not unlikely for us to go to Cork.
Our dear and much esteemed friend, Robert Valentine, is now there,
and has been very poorly; but we hear of his being better.
His companion has left him, they having gone through the nation.
I have visited all the meetings except two,
which we intend taking in our return to Dublin, which I hope will be in the right time;
for what matters it when or where we are, so we be but where and what we ought;
and thus far I believe it is so.
Had I come sooner here, I might have suffered less; but I can truly say,
that I preferred my Master`'s work before my own ease,
and was desirous of finishing my visit, or nearly so, before I stopped for relief,
not knowing what the consequence would be; but as I am now so bravely,
I am willing to hope to be favoured with seeing you, my near and dear connections,
once more; and if not, I wish you to be content.
Sometimes I have longed to be unclothed of this poor mortal body,
as I have often had my mind covered as with immortality and eternal life, and could say,
that a glorious crown and an everlasting song was before me.
O, my dears, I beg of you all to labour so as to have the same in your experience.
I know that all of you have often tasted with me of the good word of life,
and of the powers of the world to come; oh! let us not fall away,
but stand fast in that faith that was delivered to the saints,
and has been delivered unto us, whereby they did, and we may, obtain the victory.
Well, I am glad that in my thus moving along, I feel you near, as indeed I often do;
and now can I salute you all in a degree of that love which changes not,
and I still remain a faithful wife to my dear husband,
and an affectionate mother to all my dear children.

--

We stayed over first-day, and on second-day went to Waterford,
in which city we had much exercise,
yet were so favoured that our visit was very acceptable to our friends, and, I hope,
of some service.
I think we visited more than fifty families, and had many satisfactory opportunities,
both public and private; and being both confined with fever more than twelve days,
our stay was long.
A very humbling dispensation it was to us; yet were we so united to many of our friends,
and felt such an increase of pure love towards them, that our parting was with tears,
sweetened, however, with that peace which the world can neither give nor take away.

[.offset]
+++[+++The following appears to have been written about this time.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband and Children.

[.signed-section-context-open]
Clonmel, Third month, 1783.

I can now inform you of my recovery, not having much relapsed since I wrote before,
and both of us are bravely every way,
having been graciously helped through some very trying dispensations;
no doubt for our own good, and, I do believe,
for the help of many who have with meekness received the ingrafted word.
How have we rejoiced with such; and great has been our joy in the God of our salvation;
and thus have all our bitter cups been sweetened.
And how frequently does my spirit visit you,
having also a belief that you often think of me.
Strong are my desires, that you all may witness an increase of that which is of God,
having the wisdom that is pure and peaceable, gentle, and easy to be entreated,
full of love, and abundant in good fruits;
knowing the old man with all his corrupt deeds to be put off,
and being clothed with the new man Christ Jesus,
whose fruits are unto holiness and the end everlasting life.

--

On second-day, the 26th, we came to Clonmel,
and were very kindly received by our friends Samuel and Margaret Grubb:
here we had to enter into the arduous labour of visiting families,
which was accomplished to satisfaction.
We visited more than thirty families, and had some satisfactory meetings,
besides visiting some families in the country, and got to Youghal on seventh-day,
the 15th of third month, being the time of the province meeting.
On first-day we attended both meetings,
and had the company of some valuable Friends from several parts of the province.

On second-day, being favoured with best help, we had a satisfactory meeting;
we stayed over their meeting on third-day, and were well satisfied in so doing.
On fourth-day we arrived at Cork, staying in and near there about four weeks;
visited above fifty families, and had some good service.
From there we went to Limerick, and stayed about a week, had some satisfactory meetings,
and visited several families; from there to Ross,
and were much favoured among a poor few; then to Mountmellick,
and were well satisfied with staying meeting there,
and had the company of John Ridgway before we left.
We were at meeting at Ballitore on first-day.

[.offset]
+++[+++At Ballitore she writes to her family, as follows:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ballitore, Fourth month 26th, 1783.

I have hitherto been helped with best help,
so as faithfully to discharge my duty in all the
meetings I have been at since I came into this nation;
and I think we have been at all the places where meetings are constantly held,
except one, which we intend to take on our way to Dublin,
where the Half-year`'s National Meeting is to begin.
O that I may finish well! is the breathing of my humble, thankful soul.

I long to fix a time for my return,
but cannot tell how long we may be detained in Dublin; having frequently been in bonds,
as ambassadors who have to declare the way of life and salvation.
I desire that you will with me learn patience and resignation to the Divine will,
as we well know, that it is the will and power of God which is our sanctification; and,
my dears, you, with me, are very sensible that our time here will soon be over;
therefore let us cheer up our drooping spirits, and not sink below hope,
but ever witness it to be a safe anchor to our souls.
Though one fall on one hand, and another on the other, yet let us remember,
that the foundation of God stands sure,
having this seal--'`The Lord knows them that are his.`'

I feel very near to you all, and though absent in body, yet very often present in spirit;
and sure I am, that we have been baptized into the one Spirit,
and have drank of the one cup, even the cup of blessing,
by which our many bitters have been often sweetened,
and we have blessed that name which alone is worthy of thanksgiving and praise.
I beg that we may ever rely upon, and live in pure obedience unto Him,
who can subject our natural wills,
and change the very nature of the lion into that of the lamb;
and how pleasant is our dwelling, when upon God`'s holy mountain,
where nothing can hurt or destroy.

--

On third-day had a meeting at Baltiboys.

We reached Dublin, and were at the Quarterly Meeting for the province,
and at the National Half-year`'s Meeting;
during the course of which we had some edifying seasons; but, alas! here,
and almost everywhere else in this country, things are very low,
and truth is trampled underfoot.
We were favoured with the company of William Rathbone, of Liverpool,
and with that of many valuable Friends of this nation, of whom we took a long farewell.
I had felt an engagement of mind to attend the Quarterly
Meeting at Moyallen--the trial was great,
as some Friends were going to England: my companion, too, was ill of a cold,
and not able to move away for a few days,
so that we did not take all the meetings we had intended.
I had, however, one more opportunity of sitting with Friends in Dublin,
which was greatly to my satisfaction, and I took a solemn and final farewell of many.
On the 15th of fifth month, we commenced our journey,
having the company of our worthy friend, James Christy, who had waited for us.
He has gone with us many long journeys:--I think I had his company six weeks,
and he is nearly eighty years of age.
On sixth-day we reached his pleasant habitation.
We then attended meetings at Lurgan, Grange, Ballyhagan and Moyallen; the Select Meeting,
on sixth-day, the Quarterly Meeting on seventh,
and a very large meeting for worship on first-day,
in all of which we were favoured with best help, and the conclusion was satisfactory.
We took a solemn leave of many,
and had some opportunities to edification and comfort with our beloved friends.

[.offset]
+++[+++On the 26th she arrived in Dublin, where she wrote to her son.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Dublin, Fifth month, 1783.

I was glad of your letter,
and to hear of our solemn parting being had in remembrance by you; and you, my son,
with many who were there present, are also remembered by me.
Oh! that pure cementing love may so prevail in all our hearts,
as to melt us down again and again, until all the dross be done away,
and all the reprobate silver removed, and we be as pure gold, not only in lustre,
but having the full weight; then we shall not only be of the called,
but the chosen of God, serviceable in his church, as firm stakes in our Zion,
useful vessels in the Lord`'s house; and our conduct will proclaim holiness to his name.

--

The next day several of our friends came, and we were favoured together,
and parted in that true love and holy fellowship that will never end.

On fifth-day, the 28th, we went on board the packet,
being accompanied by Joseph Williams, of Dublin, Richard Shackleton, and John Russel,
from Moate, who were on their way to the Yearly Meeting of London.
On seventh-day we arrived safe at the head,
and immediately proceeded to Colebrook-dale.--Here we had a meeting on third-day;
afterwards attended meetings at Newdale, Brolley, and Shrewsbury, all, I think,
to much satisfaction.
Here my dear companion, Ann Byrd, and I parted; she returning homeward,
and I to the Bank, with my kind friend, Rebecca Reynolds.
In our travel on first-day, the 8th, though much shaken with the rough and uneven road,
we had a remarkably favoured opportunity,
which in silence and testimony held more than two hours;
and as such a season in a stage coach is not common, I thought fit to mention it.
On the 13th of sixth month, 1783, I got safe home,
and found my dear husband and children all well; for which favour,
and for the blessing of preservation both by sea and land, I am, and desire always to be,
humbly thankful unto the God and Father of all our mercies,
who is ever worthy of thanksgiving and praise.
Amen.

[.offset]
+++[+++About this period we have this remembrance of her beloved family.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Sheffield, Eighth month, 1784.

I can truly salute you in a degree of our heavenly Father`'s love,
daily breathing unto Him in secret for help for myself and for you,
that we may be strengthened, and may know an increase of faith,
and a decrease of unbelief, which at times is ready to enter, and if given way to,
would lay waste all that ever has been done in us for the good cause of Truth.
Oh that nothing may be permitted to hinder our perseverance therein!
I find it as needful now to be upon my watch as ever, desiring that I may do no harm,
as I seem not capable of doing much good.
Yet I feel bound to duty,
and sit as a sentinel not daring to move out of the right course.
O, my dears, think of me, for I am sorely buffeted and in a continued warfare; and yet,
at times, am favoured with an unshaken hope of obtaining the victory over death, hell,
and the grave.

--
