[#testimony-nottingham, short="Testimony from Nottingham Monthly Meeting"]
== Testimony from Nottingham Monthly Meeting, concerning Ruth Follows

This our dear ancient friend, was the daughter of Richard and Ruth Alcock, of Weston,
in Nottinghamshire, exemplary members of our Society,
who endeavoured to train her up in a religious life and conduct; yet,
it appears from some of her memorandums,
that she forsook their counsel and deviated from the simplicity of Truth,
when very young; but being favoured with Divine visitations,
she was humbled and brought near to the Lord, and in love with his chastisements.

In this state she was enabled, first to overcome one thing and then another,
and expresses herself thus:--"`Oh the peace that my poor soul enjoyed
when favoured with the presence of the Almighty! then could I say
rejoicing--'`In your presence there is joy,
and at your right hand there are rivers of pleasure, and that forevermore.`'`"

About the twenty-third year of her age, she was united in marriage to George Follows,
of Castle Donnington, with whom she lived in much harmony more than sixty years,
and though both of them were in low circumstances,
yet being first concerned to seek the kingdom of heaven and its righteousness,
they were blessed with health and strength to labour honestly for their support,
and witnessed the fulfilment of the promise, that all things needful should be added.

About the thirtieth year of her age, after much close exercise of mind,
she was made willing to appear in public testimony and soon afterwards
believed it her duty to travel in the work of the ministry,
and at different times visited most of the meetings of Friends in this nation,
and was twice in Ireland.

In her conduct she was truly exemplary: she was a diligent attender of meetings,
even when very infirm; a sound minister, reverently waiting for a right qualification:
her testimony was lively, clear and edifying,
reaching to the witness in the minds of many.
She was a sharp instrument in the Lord`'s hand against
everything that defiled his house,
and very desirous that the camp might be kept clean:--her
words were accompanied with power,
encouraging the faithful to hold on their way, and the unfaithful to return,
repent and live.

Being gradually on the decline for some years, she suffered little bodily pain;
and having done her days`' work in the day time,
was favoured with a happy calm at the close of life.

On the 3rd day of fourth month, in the ninety-first year of her age,
she quietly departed; and on the 10th was interred in Friends`' burying-ground,
at Castle Donnington, in the county of Leicester.
