== Chapter I

[.chapter-synopsis]
* An account of her early experience, including a few journeys after her first appearance in the ministry

A short account of the Lord`'s tender dealings with me,
and how he visited my poor soul when very young in years:

My dear parents taught me, both by example and precept, to live a sober and godly life.
My dear mother bore a faithful testimony to the blessed Truth,
according to the manifestation received from God,
who enabled her to be as a standard-bearer for his holy name; and I believe I may say,
she has laid down her head in peace, and is at rest from her labours.
Although I had such parents, and was accounted much like my dear mother,
yet after she was taken from us I left her counsel behind me,
trod her testimony under my feet and took a large swing in vanity,
frequenting such company as had like to have proved my utter ruin.
But blessed be the Lord! he closely followed me with his sharp reproofs,
and forever let my soul praise his holy name! stopped me in the midst of my career,
and took off my chariot wheels,
so that I could not overthrow nor yet keep the pure Seed in bondage;
for he was pleased to let me see my state,
and very often did he make me to confess my sins before him,
and with tears implore his mercy; and I can truly say,
I witnessed him to be a God hearing prayer.
But, oh! yet was I unwilling to forsake my iniquity, and was for reserving a part,
such as I best liked;
but the Lord who calls for the whole heart would
not accept of a half-offering--Agag must be slain,
and all that appertains to Amalek.

Thus was the Lord pleased to visit and revisit me;
and truly do I desire that I may never forget his mercies,
which have been so very largely extended towards me.
And blessed be his holy name!
I was enabled through the might of his power,
first to overcome one thing and then another;
so that by degrees I was brought near to the Lord, and made to love his chastisements.
O,
the peace that my poor soul enjoyed when favoured with the
presence of the Almighty! then could I say with rejoicing,
"`in your presence is fulness of joy;
at your right hand there are pleasures forevermore.`"

As I was thus made willing to obey the Lord, he was pleased to bless my undertakings;
and about the twenty-third year of my age I was married
to a young man far more worthy than myself;
and I can truly say,
it was because he was well inclined that I had so
much love for him as to have him for my husband:
and as it was our concern first to seek "`the kingdom of God,
and his righteousness,`" kind Providence was pleased to bless us with health and strength,
so that we could honestly labour for the support of our bodies,
we not having much else to trust to but our own industry.
As our desire continued not to esteem these lower enjoyments above those that are unchangeable,
but having food and raiment to be therewith content,
so I can say we have not been lacking, but have been favoured beyond what we did expect;
and as we really loved the company of good Friends, several were sent to visit us,
with whom we had comfortable meetings.
How have our souls been refreshed in the love of our God,
for which we have cause to bless his holy name,
and to be truly thankful that he has been pleased to send his servants among us;
desiring that he may still raise up more such worthies, who may be as valiants in Israel.

As I was thus brought near to the Lord and his people,
he was pleased to show me that he had further service for me to do,
which was to bear a public testimony for his name.
But oh! the exercise this brought upon me, for I found self was yet for being pleased;
I was not willing to be counted a fool,
and was for being almost anything so that the Lord would be pleased without this,
that I might not become a gazing-stock to the world: but the more I strove against it,
the heavier was my exercise.
The Lord was pleased to afflict me in a wonderful manner,
which bowed my soul even to the earth,
and in the midst of this trouble I was made to cry
in the bitterness of my poor afflicted soul,
"`O Lord, make me what you would have me to be--lay me even with the dust,
but be pleased to raise me up again, and let me enjoy your presence as in days past.`"

Thus did the Lord work in me,
and by the might of his power made we willing to become a fool or anything,
for his name`'s sake.
O, what peace did my soul enjoy,
when I had given up in pure obedience to the Lord`'s requirings,
which was about the beginning of the twelfth month, 1747,
when my mouth was first opened in a public manner at our weekday meeting at Castle Donnington,
I being then about the thirtieth year of my age.

In a little time after, I heard that Elizabeth Fletcher, a Friend in Derbyshire,
had a concern on her mind to visit the counties of Huntingdon, Cambridge, Norfolk,
Suffolk and Essex, so to London, in order to visit that great city,
and was inquiring where she might meet with a companion who had the same concern.
This took such hold of me when I first heard of it, that it struck like a dart;
but I would not have consented to it, if I could have had peace in the refusal;
for I let in many reasonings against it, and thought but few like me travelled,
and could not see how way was to be made without a great
deal of trouble;--and having just appeared in the ministry,
and being a poor weak creature in spiritual things,
I could not think what service I could be of to any,
except it were to Elizabeth Fletcher, who was a very weakly woman.
But I was made willing to drop these reasonings, and leave all to the Lord,
who can and does make way when we can see no way;
so in obedience to his pure mind and will, I left all to his divine protection,
my dear husband and sweet babes, my eldest about six, and youngest about three years old.
I thought this a great trial, and it seemed at times to come very near my life;
but as I stood resigned to the will of God, he gave me strength in weakness,
and his holy arm bore me up through many deep exercises that I met with in this journey.

And blessed be his powerful name! the same arm that
took me from my nearest connections in life,
also brought me home again in peace; and as I was preserved,
so were my dear husband and children;
and we both have cause to give all honour and glory to God, who is alone worthy,
now and forevermore!

On this journey she wrote the following letter to her husband:

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband.

[.signed-section-context-open]
Woodbridge, 21st Third month, 1748.

In unfeigned love to you and my dear and tender children do I now write;
and although it is so ordered that we are separated one from another outwardly,
yet I am near to you in spirit.
As it is in obedience to the Lord that I am where I am,
I sincerely desire that I may continue in obedience to his pure and holy will,
although it be a very great trial, and at times comes near almost as my life.
Yet, blessed be the Lord, he has been pleased so to favour me with his living presence,
and to support me with his divine power,
that I am made willing to be what he would have me to be; and, my dear husband,
as I desire for myself, so for you, that we both be wholly resigned to his will;
and I believe, while we abide in his fear, all things will work together for our good.

--

+++[+++In the course of the journey mentioned in the foregoing account,
it appears that she attended eighty-two meetings,
in company with her friend Elizabeth Fletcher;
besides being at the Yearly Meeting at Woodbridge; leaving home the 8th of third month,
and returning the 29th of sixth month.

On the 25th of sixth month, 1749,
she again accompanied Elizabeth Fletcher on a religious visit,
and returned home on the 26th of seventh month;
having attended eleven meetings in parts of Warwickshire, Leicestershire, Worcestershire,
etc.; at three of which, Henley, Broomsgrove and Worcester,
they had the company of John Griffith.

The subsequent letters were written after her return home:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Leicester, 27th of Sixth month, 1754.

[.salutation]
Dear Friend,

I with gladness received your letter, but in the reading of it,
was seized with a concern that you are not yet emptied enough of self.
I hope, my dear friend, you will bear with me, as I must deal honestly;
and desire I may speak simply upon all occasions without
seeking to ornament it with what might please myself,
because I have learned to know that what is done to gratify self,
is displeasing to the Almighty.
It seems to me as if you were in a track that I long trod in,
therefore I am in much love engaged to tell you a little of what I have experienced.
When the Lord has been pleased to lay a concern upon me to speak among his people,
I was not willing to stand up or to kneel down, until I had as I thought,
made it somewhat compact;
and those who were my best friends have been much concerned for me,
and advised me to give up in faith, for I should never grow while I remained so.
For this cause I have been brought into great confusion,
so that I could neither go forward nor make an end in a proper manner;
if I dare have said that I would never preach more, I would have said it;
but blessed be our God, he is ready to lead us step by step,
were we but willing to follow him in humility.
Let all our actions be in his fear, without the least desire for the praise of men;
then I am satisfied he would forgive all our past offences, and love us freely.
Well, my dear friend, I seem to be near a conclusion, and also near you in spirit,
and in a degree of that love which first united us,
I sincerely salute you and bid you farewell.

--

[.signed-section-context-open]
Donnington, 18th of Ninth month, 1757.

[.salutation]
Dear Cousin,

You have at times been brought to my mind,
and I thought I had freedom to write a few lines to you,
supposing you might be at the Quarterly Meeting.
I hope you will not be negligent in attending such meetings,
nor any other which are appointed for the service of Truth,
and for the worship of Almighty God.
I pray you, let not the indifferency of others lull you asleep;
but be diligent and watchful, truly waiting in the depth of humility,
and then I doubt not but you will be favoured with the presence of God,
both to your comfort and edification;
for it is the Divine Monitor from heaven that is still the teacher of his people.
It is He that yet speaks as never man spoke, and he cannot be removed into a corner.
I hope dear cousin, you are sensible of these things,
and I desire that you may increase in wisdom.
Let it be your concern to keep a conscience void of offence both toward God and man.
This is what I desire to hear of you and my other relatives.`"

[.small-break]
'''

+++[+++From 1749 until the year 1758,
it does not appear that she was engaged in any more extended religious
service than of attending the general meetings at Atherstone and Matlock,
when,
on the 20th of eighth month she accompanied Anne
Wright into Yorkshire:--they attended forty meetings,
and the Quarterly Meeting at York; where she says, was James Wilson from Darlington,
aged ninety years, who had a deal of the service of the meeting,
and seemed to take his final farewell of the place.--She
returned home on the 15th of tenth month.]

In the twelfth month +++[+++she says,]
I had for some time drawings in my mind to Warwick,
and a few other meetings in that county,
and having acquainted the Monthly Meeting thereof, I had its approbation,
and a certificate accordingly.
I attended Leicester Quarterly Meeting,
where we were favoured with the company of George Boone and William Dodson.
From there, with G. B. Sampson Lloyd and Joseph Heath, I went to Coventry;
and on the 17th to Warwick, where was Catherine Payton, of whose company I was glad.
We were both engaged to labour among a degenerate people, but had peace for so doing,
and Friends who were truly sensible, were satisfied and seemed glad of our company.

We were at the Quarterly Meeting on second-day,
from which after attending a few more meetings, I returned home and found my family well,
for which I was thankful to my Lord and Master,
who has often seen fit to call me from it;
and although it is a pinching trial to leave dear husband and children,
yet great peace have they who are obedient to the Lord`'s requirings.
As I never had cause to repent being faithful,
and I heartily desire that all who are called of God,
anointed and appointed to preach the Gospel, would steadily walk and diligently hearken,
that they may perfectly hear the distinct sound and the true voice,
that they may not run before they are sent,
nor stay behind when they are commanded to go--then all would be well with them.

On the 21st of second month, 1759,
I went with Thomas Bakewell and his wife to our Quarterly Meeting at Leicester,
where was George Mason out of Yorkshire, of whose company we were glad,
and were truly comforted together in the love of God.

On the 26th of fourth month, was at the general meeting at Nottingham,
where was John Alderson of Yorkshire, whose company was very acceptable.

On the 14th of seventh month I went to Polesworth and Atherstone;
and on the 15th was at their general meeting,
where were Catherine Payton and many other public Friends.--On the 29th was at Matlock,
where was Samuel Fothergill, whose visit was very acceptable.
