== Chapter II

[.chapter-synopsis]
* Her visit to the meetings of Friends Westward
* To Bristol
* And from there to London

On the 28th of the second month, 1760, after a long time of deep exercise,
I parted from my dear children,
having the approbation of my friends and a certificate according to good order
to visit the meetings of Friends westward to Bristol, and from there to London.
My dear husband accompanied me a few days, first to Leicester and then to Coventry,
at which places I held no meetings, but parted with my friends in much love,
being engaged in my mind to be at Birmingham on first-day.
I was at their meetings to my satisfaction.
On the next day I parted with my dear husband, which was no small trial to me,
and being left alone and never having gone such a journey by myself,
it seemed very hard for me to bear it. But I found it best to be still,
knowing that I was engaged by and for Him
who is alone able to help and preserve His people.

From Birmingham I was at various places, attending nineteen meetings,
and on the 20th of third month reached Bristol,
where I attended six meetings before the quarterly meeting, and seven afterwards.
I then seemed to take my farewell of them to my satisfaction,
though I was an example of silence in many of their meetings.

I here feel inclined to look back upon my journey,
not having had an opportunity until now to make any remarks.
And first I find freedom to say,
for the encouragement of such as have the right cause at heart,
that I have had no cause to repent leaving home and my near and dear connections there,
for the Lord has been pleased to be with me hitherto.
I have been kindly received by Friends, and at this time a hope is afforded me
that I shall be enabled to perform the rest of my journey;
and being well assured that I am in the way of my duty, I am thankfully content.

I was favoured for a time with the company of Mary Winter, a young woman,
being young also in the ministry. She was with me at Bewdley and Bromsgrove,
and I was truly glad of her company.
I was favoured also with the company of Martha Merrill,
who stayed with me while I was at Bristol, and accompanied me to Frenchay and Earthcot;
at the latter place we parted in much love.
On seventh-day I went to Bath and lodged at Love Tyler`'s, who very kindly received me,
which made my lonesome situation much pleasanter while I remained in that town.
My great Master too,
whose servant I have been and for whom I desire that I may ever be rightly engaged,
was pleased to send my dear friends Robert and Love Peters
from Bristol to Bath on first-day morning.
O, how glad was I to see them,
for it seemed as if I could hardly live to finish that day!
But being thus favoured with agreeable company,
and again finding the Lord to be my helper,
I got through the meetings with some degree of satisfaction.
My dear friend Love Peters offered to accompany me to some meetings,
which I very thankfully accepted.
We were at nine, including the Quarterly Meeting at Cain, where we parted,
she returning with her husband who came from Bristol for her.
There were many Friends at the above meeting from several places,
but too few who were truly concerned for the cause of God,
so that they who were rightly engaged had very hard work.
But the power of the Most High was over all, and His great name was glorified.

We next proceeded to Devizes, and how hard did it seem to me to go among strangers!
I cannot express what my soul went through in that place;
I had nothing to say at meeting, neither could I see for some time how I might find ease.
I endeavoured to be still,
and cried unto the Lord in my spirit that I might be preserved,
and if it would please Him to show me what He required of me,
for I believed I would submit even if it were ever so hard to my own will.
As I thus sat, there came several to dine at the house where I was.
We sat down to dinner, and in the bitterness of my soul, at the command of the Lord,
I poured forth my supplication unto Him for their sakes, poor souls,
who were living in forgetfulness of God. Yet, even in this condition,
the Lord visited them in this way,
and engaged me to pray for them; and by my obedience I had peace.
O, how thankful was I that I could leave the town with satisfaction!

From Devizes I went to Marlborough,
though still in dread and fear lest I should not be able to stand my ground.
But blessed be the Lord who has thus been pleased to lead me,
even as through the valley of the shadow of death. He stood by me,
and I was enabled to get safely through my visit to this town.
From there I travelled to Newberry and Backhurst, and Reading.
There I attended their Half-year`'s Meeting,
with which I was well satisfied; many worthy Friends were present,
one of whom was Joseph White, from America.

I then proceeded towards London, where
I continued nearly six weeks visiting the different meetings in the city and neighborhood.
Finding myself at liberty when the Yearly Meeting was over.
I parted from many Friends in much love and satisfaction,
some of whom I had then first become acquainted with.
Among these was Susannah Hatton from Ireland, a widow,
who was intending to visit America, and had left six children.
My friend Anne Wright was nearly two weeks at John Cartledge`'s in Wood street,
and together we visited several families, to much satisfaction.
May that love ever remain with them in which we were truly united;
and although we may be outwardly separated,
yet we are as epistles written in one another`'s minds.
Oh, that we may keep near to the Fountain of love and life! Then we
shall have cause to rejoice together in the communion of the one pure Spirit,
which is extended to the whole family of God, the world over.
Amen.

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband.

[.signed-section-context-open]
London, Fourth month, 25th, 1760.

I am still satisfied that I am about my Father`'s business,
and for your comfort may inform you that I now enjoy peace,
and desire that we may be enabled to do our duty to Him from whom all our blessings come.
I was at Gracechurch street meeting today, and came away in peace;
Isaac Sharpless was there in the morning, and we were comforted together.
His concern has been to visit families,
and he has gotten through thus far as to believe he will be at liberty to go home tomorrow,
having been at many places and families, although only here a little more than a week.
By his labour he has made way for others who had the same concern,
but perhaps could not so well begin that great work.
In looking back a little to my visit at Bristol,
the place where I have often been concerned,
it was not without a cause that my service there should be in a manner I did not expect.
I laboured diligently and was baptized often because of the sins of the people,
and brought near to the mourners in Zion,
and I feel my spirit drawn towards them even as I write.
It is pleasant to me to think of them,
for we were joined in a holy fellowship which will endure.
I visited many families,
in which engagement I had freedom to join Martha Merrill and Love Peters.
I had to admire how the states of those I visited were brought before me,
and although I found it hard work to believe my Lord,
His mighty power did enable me to do His will,
for which I am truly thankful. The love of God did so prevail that many were bowed,
and seemed to be brought near to us in spirit.
Although I have been thus favoured, yet fear and weakness encompass me,
so that at times I am ready to faint and seem like one who has not known good.
Oh, may the fear of the Lord, which is a fountain of life,
ever preserve us from the snares of death!
May we who have known redemption in some degree,
never more be entangled with the yoke of bondage.footnote:[Galatians 5:1]
May we be favoured with food and raiment,
and a blessing upon our tender offspring from the Holy Spirit,
which has and does conduct us, and may this good Spirit rest upon our children.
This I desire for them and us more than uncertain riches, which will fade away.
My mind is very closely engaged, often in great painfulness and watchings,
lest the enemy, who daily lays snares before me,
should so prevail as to cause me to do anything that
would occasion the honest-minded to be uneasy.
Oh, the proving seasons I have met with, but which I hope are all for my good,
and the good of many in this place! Surely you, along with my dear friends,
will have a concern to pray for me.

--

On 4th of sixth month I left London and went with our friend John Griffith
to his house at Chelmsford. I stayed their first-day meeting,
where I was again favoured with the company of Susannah Hatton.
With these Friends I proceeded to the Yearly Meeting at Colchester,
after which we again parted, and on the next first-day I was at Ipswich.
From there I travelled to Woodbridge Yearly Meeting, and on the 18th to Yarmouth.
Next I went to Norwich, where I lodged at Samuel Gurney`'s,
and was at many meetings with many worthy Friends.
Then in company with Mary Gurney, I went to North Walsham,
from which place my worthy friend John Ransom went with me to several meetings.
I was truly glad of his company, and hope I may not forget his kindness to me.

We returned to Norwich the 12th of the seventh month,
where I mostly continued till the 7th of the ninth,
when I parted with my dear friend with whom I had been so unexpectedly detained.
It was very contrary to my own will, and might seem strange to many,
but I believe it was according to the will of God.
For His cause did I mourn with them that mourned, yea, I was very often in sorrow;
a time of deep searching of heart it was to me. But, blessed be the Lord,
He was pleased, after He had thus tried me
and found me in sincerity truly desiring that I might not be deceived,
but that His will might be done, I say, after all this time of proving,
He let me see my way again. And when the cloud was removed from my tabernacle,
I went on my way rejoicing.
My friend John Lucas accompanied me until I came to Lynn;
from there I went to Downham to their general meeting,
where I met David Coulson and William Dodson.
Proceeding to several places I came to Godmanchester, where was Samuel Spavold.
Afterwards I proceeded homeward, and arrived there the 15th of ninth month, 1760.

[.small-break]
'''

+++[+++The following letter is a further description of the close
conflict she endured in being detained at Norwich:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Norwich, Eighth month 18th, 1760.

It seems very hard for me to tell you that I am yet bound in this place,
although when I wrote to you I thought that I might have got away.
It is not omission of duty that detains me,
but surely it is for a trial of my patience and of yours, for a cause we know not.
I fear we have been over-anxious,
yet sometimes I have hopes that you are more resigned
to the will of the Most High than I am.
If I be rightly sensible, I believe that I am where I ought to be;
and although I would have hid the concern, yet I could not,
for several Friends whose spirits are united with mine,
and who had a sense of my travail of soul--came to see me. And my dear friends
with whom I make this long abode told me they believed I was not clear to go,
and my unwillingness to stay made my affliction heavier, which indeed was true.
Friends are very kind and loving to me,
and seem glad to see me and tell me they are not weary of me.
When I consider how it was formerly,
when our worthy ancients who were concerned to speak in the name of the Lord
were haled to prisons, abused, and had all they had taken from them, yea,
and that many sealed their testimony with their blood, what can I say?
There hardly seems room for us to complain;
our trials seem so trifling compared with those which they met with,
and looking at what many are tried with now, as to going overseas,
oh, my heart is often affected for them!
Yet how unwilling I am to be thus confined in my native land,
which seems but little to engage with compared to the trials of those who cross the mighty ocean.
Therefore, as it thus happens for me to be tried in this way,
I beg that you may still resign me, for
how affecting would it be to us both to bring a burden home with me.
O that it may not be so! It would be better for you to see me no more,
than to see me in that anxiety of soul which disobedience brings.
Therefore be comforted, for although we may have been tossed as with a tempest,
yet our foundation is sure, against which the gates of hell shall never prevail.
May we ever remain upon it.

--

30th of seventh month,
1761--Although I have not written anything down of my travels for many months,
yet I have not been idle,
but have had an afflicting time, so that I could not go far from home except
when I was able to get to our own Quarterly Meetings.
In the sixth month, Joseph White (from America) was at our meeting,
and I, with other Friends,
were with him at Soilby and Dalby.--In the seventh month my husband took me to Nottingham,
I being engaged for Lincoln Quarterly Meeting, where were John Griffith, John Hunt,
Thomas Corbin, Joseph Taylor and Joseph Roe,
on an appointment from the Yearly Meeting to visit the Monthly and Quarterly
Meetings in several counties. Their company was very acceptable.
After my return home, I attended the Atherstone general meeting.
