== Chapter V

[.chapter-synopsis]
* Her visit to some South and South-east counties
* Also to London, the Land`'s-end, etc.

In 1765 I felt a concern to visit some
meetings in some Southern and South-east counties,
and the Yearly Meeting of London.
I therefore laid my concern before Friends and had their approbation
and a certificate accordingly, not then knowing of a companion.
But in the fourth month I went to a general meeting at Breck,
in Derbyshire, and there providentially met with Sarah Taylor, of Manchester,
who was going the same way.
We were at Nottingham at the Quarterly and Yearly Meetings, much to our satisfaction,
but not being set out on my intended journey,
I returned home a few days and parted with my dear children.
My husband accompanied me to Leicester, where we separated.
I proceeded to Oakham and had a meeting; from there to Godmanchester and to Ramsey,
where I met with my companion, Sarah Taylor.
We attended several meetings in our way to London,
and many in that city before the Yearly Meeting,
and stayed some little time after its conclusion.
We then went to Bromley, and lodged at Robert Forster`'s;
from there to Chelmsford to John Griffith`'s,
who was then very ill but recovered shortly after, and I believe went to America.

[.offset]
+++[+++The following letters appear to have been penned about this period:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, Sixth month 1st, 1765.

&hellip; And you my son, whom with the rest of my children I dearly love,
let me entreat you to be constant in your pursuit after stability of mind.
Allow not your own will to prevail, but learn meekness, exercise patience,
and let your moderation in all things appear;
inasmuch as you know that '`the Lord is at hand.`' Let me again advise
you to '`study to be quiet and mind your own business.`'
'`Be swift to hear and slow to speak;`' let your mind be often gathered into silence,
and your desires more after communion with God than with men.
I hope these hints will be observed by you,
and as you love and seek after true retirement,
you will be favoured with clear instructions;
therefore to the holy guidance of the pure Spirit of Christ I recommend you.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband.

[.signed-section-context-open]
London, Sixth month 14th, 1765.

O that we may be more and more concerned to watch against every
appearance of evil--be willing to be what we ought to be,
and do what we ought to do.
This is my daily concern for myself, who am still surrounded with weakness,
and slavish fear has too much prevailed.
My poor soul has often been in bitterness,
fearing lest the Divine Hand would no more strive with me.
Yet I hope a sincerity remains in my heart,
and the Lord in His tender mercy has had compassion on me,
and enabled me to speak well of His name.
O that I may keep in the way of my duty, and faithfully discharge the same;
then peace will assuredly be my portion.
Therefore I feel desirous that we may more and more unite in a godly concern
with our dear children and the few Friends who remain alive,
that so our strength may again be renewed.
Let us learn patience and wait for it; and when able, pray for resignation,
and not marvel at the fiery trials that we may meet with,
for so it has been with the righteous of all generations from the beginning of the world.

--

We then went to Coggeshall, Colchester, Needham, and to the Yearly Meeting at Norwich.
We stayed here and in the neighbourhood several weeks, and as in other places,
had hard labour; yet in our journey we have had many satisfactory meetings,
visiting most of those in Norfolk and many in Suffolk. We
came pretty direct from Lynn to Wisbeach,
Spalding, Broughton, Stableforth and Nottingham, where my husband met me.

I think I may say
that my foregoing journey was in the Lord`'s time and according to His will,
and I was favoured with a companion who indeed
was a helpmate in the good cause for which we were both engaged;
and as we faithfully laboured therein, we enjoyed much peace.
Yet as it was formerly so it is now--many are the trials of those who are truly concerned,
and above all, still prefer Jerusalem above their chiefest joy.
O that I may be enabled to struggle through the many
difficulties which it is my lot to experience;
but doubtless, they are permitted for good.
Meeting with some close trials, I had great difficulty after my return home,
to keep my mind in any degree of quiet. But considering that I had been, so far as I knew,
in the way of my duty, I saw I must learn patience.
I endeavoured to submit to the all-wise Disposer of events,
who will do as He sees fit with us His poor creatures,
and surely it is good for us to be tried and proved.
And as in this sore time of conflict I could not find that the things
which had befallen us were any way through any neglect of mine,
but in the ordering of Providence, therefore did I look again to Him for help;
and in His mercy He looked down upon me, and once more delivered my soul.
Then did His peace return, and again was I engaged to visit some of my brethren,
and went to our Quarterly Meeting at Leicester,
where my Lord and Master favoured me with His presence,
and enabled me to praise His holy name.
I also went to the Quarterly Meeting at Wellingborough,
where I had some service for the Truth and returned home in peace.

On the 20th of sixth month, 1768, I attended the Quarterly Meeting at Coventry,
where were Samuel Geulea of Bristol, and Hannah Bevington of Worcester,
who had a concern to visit the families of Friends in this county.
I also found it my duty to join with them in this close exercise,
and did not leave them until the visit was performed, which ended at Eddington,
where we parted, having been made helpful one unto another,
and very often as one another`'s joy in the Lord.
It was by the help of His power that we were carried through so great a work.
And as it was at seasons very edifying and comfortable to ourselves,
so we have cause to believe it was a time of favour to many,
and the great name of our God was glorified.
With His peace in our bosoms we returned,
and I arrived at my habitation after an absence of nine weeks.

On the 22nd of ninth month, 1769, I was at our Quarterly Meeting at Leicester.
On first-day I was at Wigston,
and in the evening had a large and satisfactory meeting at Oadby
with the people of that village, who behaved very well.
From there I travelled by Wigston and Nuneaton to Coventry,
and attended their meeting on fourth-day,
which was a very trying one to me;
and I was given to understand that I had caused uneasiness
by making some sort of preamble and needless apology,
which I was not sensible of until after being told.
Then by a deep consideration and thorough self-examination I found myself guilty,
and much exercise and many a painful hour it cost me.
Oh, how I was covered with shame! But I was favoured with true repentance,
and again received into favour.
I leave this as a caution to such as may see these lines,
desiring that none may slight advice which is intended for good,
although it may seem to be given sharply.

[.offset]
+++[+++From the following letter it appears she was on a visit at Norwich:]

[.embedded-content-document.letter]
--

[.letter-heading]
To The Same.

[.signed-section-context-open]
Norwich, Sixth month 3rd, 1770.

As a tribulated path is our lot, I would have us learn contentment therein,
as we have the comfortable assurance in ourselves of having endeavoured to do our part.
Let us remember to put in practice the good advice of our worthy friend Samuel Emlen,
which was to commit ourselves and all we have into the hand of Him who can turn
the heart of man as a man turns the water-course in his field. We see
that by our over-thoughtfulness we cannot add one cubit to our stature,
nor make one hair white or black.
I have a hope that things will appear rather pleasanter in time,
and if we faithfully follow our holy Captain unto the end of this short race,
we then shall inhabit a glorious eternity.
Let not your spirit sink too low, neither be too much troubled, for it is certain
that in our Father`'s house are many dwelling places. Therefore be of good cheer;
I have hope that we shall be enabled to overcome this wicked world, as many have done.
I hope my dear J+++______+++ will be with you when you receive this.
I should be glad to hear of a suitable place for him, but do not know how to advise.
If he would only take my counsel, and choose good and refuse evil,
then peace would flow in his soul as a river and righteousness as a mighty stream.
That this may be the experience of us all is the travail of my soul.

--

Twelfth month 13th, 1770, I attended our Quarterly Meeting at Leicester;
from there to Coventry, and to the Quarterly Meeting at Warwick.
On the 18th was at Wigston with John Burgess, where I remained some days.
On the 23rd was at the meeting at Leicester,
and finding that I must now proceed on a longer journey
that had for some time rested upon my mind,
I wrote home for a certificate to meet me in London,
feeling engaged to attend several Quarterly Meetings.
On the 24th I proceeded to Oadby, Drayton and Northampton, and was at their Quarterly Meeting,
where were Joseph Worcester and Thomas Ball from Buckinghamshire.
Proceeded to Ackley, and lodged at Thomas Buck`'s, going afterwards to Buckingham,
with Joseph Worcester.
From there to Oxford, where I met with George Boone, was at their meetings on first-day,
and the Quarterly Meeting on second-day. From there I went with Thomas Hull and Robert Eells
to Thame, and on the 1st of first month, 1771,
was at the Quarterly Meeting at Aylesbury. That evening I went to High Wycombe,
very much wearied.
I lodged at Joseph Stevens`', who had five daughters and two sons, all grown up;
they were very friendly, and such a family as we seldom see.
They and their parents live together.
On fifth-day I was at Amersham, and returned to an evening meeting at Wycombe.
From there I went with Joseph Worcester to Uxbridge, to my kind friend John Hull`'s,
and here my kind friend Rebecca Stevens came.
I attended their meetings on first-day, and on the fourth
was accompanied by Thomas Hull and his wife to Staines,
and remained several days with the widow Finch,
whose husband died suddenly a few weeks ago.

On the 14th of first month I came to London,
and lodged at Joseph Roe`'s. I stayed in and around London eight weeks,
and was diligent in attending meetings during that time. I also was at Tottenham,
Plaistow and Bromley, and visited many families.
And by endeavouring to discharge my duty faithfully, peace was my reward,
and many hearts rejoiced at times with mine in this my visit.
My kind friends Joseph Roe and his wife accompanied me to Colchester,
finding liberty to pay my children a visit, my son Richard being settled at Norwich,
and my youngest an apprentice at Yarmouth. On the way I attended meetings at Chelmsford,
Colchester, and the Quarterly Meeting at Ipswich, and from there to Needham,
from which place my beloved friend Martha Alexander
accompanied me to Norwich and Yarmouth.
I was at the Quarterly Meeting at Norwich,
and my stay in this city was longer than I intended,
my children having need of my assistance on account of the illness of my granddaughter.
I also had deep travail and very hard labour in many meetings in this city,
and many times at Yarmouth. And although things are much out of order in most places,
yet we had many satisfactory meetings, some of them silent.
I stayed for the Yearly Meeting in Norwich, which lasted three days,
and then left for Bury and Godmanchester. On the 24th I travelled to Northampton,
where I attended their Quarterly and Yearly Meetings, and from there went to Drayton and Oadby,
and on the 29th at Wigston, where my husband met me,
and we got safe home the 1st of seventh month.

[.small-break]
'''

+++[+++In 1772 she was from home,
of which we have no other account but this letter written at East Markham to her husband:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
East Markham, Sixth month 18th, 1772.

You will be surprised at my long stay in and about
this city--it has caused deep searching of heart,
and has been a time of humiliation to me.
The Lord alone knows for what cause;
yet I am thankful that He has been pleased to give me
evidence that I have acted according to His will,
and therefore I enjoy His peace, which I value more than all outward enjoyments.
Nevertheless, I am often thoughtful about you and my dear children,
and when I feel strength, am engaged to pray for you as well as for myself,
that patience may be granted.
I hope you are at times engaged for me, who am as a wandering pilgrim;
yet as it is according to the will of God, I desire that we may submit.
Though our love for each other does--and I trust ever will--remain,
we must yet know a being separated outwardly.
This seems to be a weaning time, a time that I hope I may never forget;
for although the Lord has been pleased to prove me many times, as with bitter waters,
in order to keep me humble, yet blessed be His holy name,
He has also caused the spring of life to arise, and in the flowings thereof,
I have had to praise His name in the congregations of His people.

It seems as if my face will soon be set homeward, but I pray for patience,
that the latter end of my journey may not lay waste the forepart.
Having hitherto been preserved in the way of my duty, may it be so to the end,
and that we may meet with joy is the prayer of my soul.

--

On the 18th of third month, 1773,
I left home with the approbation and true unity of my friends,
with an intention to visit several counties to the Land`'s-end, in Cornwall.
My dear husband went with me to our Quarterly Meeting at Leicester, where we parted.
I proceeded to Coventry, from there to Birmingham, and attended their Quarterly Meeting.
Here I stayed a week, satisfied that I was in the way of my duty so far,
having had some deep travail, but by faithful obedience sweet peace.
On the 29th, Samuel Baker went with me to Dudley, where there was a large meeting,
the people of the town coming in, and it was indeed a good opportunity.
From there I was accompanied by James Payton to Stourbridge.
Was afterwards at seven other towns, having meetings in each,
and although deep travail is generally my lot,
yet being mercifully favoured with Divine help to discharge my duty,
my soul enjoys much peace.
At Sudbury I attended both their meetings on first-day, and then proceeded to Bristol,
where I stayed several weeks.
Attended the Monthly Meeting at Bath,
where I met Sarah Morris and her companion from America, of whose company I was glad,
and many comfortable opportunities we had together in Bristol,
both in meetings and families.
On the 13th of fifth month I accompanied them to King`'s Weston,
where there was a large and satisfactory meeting,
and here we parted in much nearness of spirit.

On the 16th I was at Clareham meeting, and in the evening at Sidcot;
from there I went to the Monthly Meeting at Bridgewater, lodged at Joseph Ball`'s,
and was afterwards at meetings at Taunton and Bridgewater.
We had several satisfactory meetings in the foregoing journey,
though there is cause for painful labour, which I have deeply felt;
but I was helped to discharge my duty,
and am brought near to such as faithfully labour with me.
I was next at Minehead, Spisom and Uffcolme,
and was accompanied by our worthy friend Ann Byrd to Wellington,
whom having now for a companion, we went to Collumpton on the 26th,
and had a meeting the same day. Afterwards we proceeded to Exeter, where,
although there are many who have neither the form nor the possession of the Truth,
our good Lord caused His power to be manifested among us.

Proceeding on our journey to Kingsbridge, we stopped and dined at Newton Bushel,
at which town live two or three of our name,
but we only saw one poor woman who met us in the street and accompanied us to our inn,
where we had a satisfactory opportunity.
We lodged at John Morris`'s at Kingsbridge and had a meeting there,
after which he went with us to Plymouth.
We crossed the passage at Salt Ash, intending for Germains,
where we arrived on the 3rd and had a meeting,
and were at Liskeard at their meeting on first-day.
From there we went by Castle Penryn to Falmouth,
where we stayed and visited several families, as we had done at some other places,
and found here and there a few who lived in the Truth. But oh, how few, as they are,
for the most part, so leavened with the spirit of this world,
that painful indeed was our labour among them.
But our great Master,
who sent us thus to visit His own and led us into deep suffering with His seed,
gave us a clear sight of the state of the church.
Some that had ears did hear what the Spirit said;
and as we were favoured with strength to discharge our duty,
our souls were filled with sweet peace, which is the only reward we labour for.

[.offset]
+++[+++From Bradford she wrote to her husband:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Bradford, Sixth month 7th, 1773.

I think I can salute you in that love that wishes your health and salvation,
and I may inform you of my welfare, with that of my near and dear companion.
We have thus far travelled in safety, and as far as we know, Friends have true unity with us,
and having true peace in ourselves, we endeavour to be content.
Though deep travail and very close exercise is our lot,
yet we have at times had to rejoice in the God of our salvation,
feeling His mighty power to be over all.
We met with our valuable friends William and Esther Tuke at Chesterfield.
They intended being at Loughborough; I should be glad to hear of your seeing them.
If I have ever moved rightly in the work I am engaged in, or had an undoubted evidence of it,
we have had it thus far in this great and solemn undertaking.
Having to believe that poor M. W. moved right,
and that we are joined in such a bond as will not easily be broken,
and as we are thus made true helpmeets,
I desire not that any man in his own wisdom should put us asunder.
Yet a close exercise having befallen us,
many tears have been shed by us on this occasion.
But I hope it may not hinder our service, for we still feel engaged to proceed,
and have been favoured again with the presence of the living God,
who alone can sweeten our bitter cups.
And I have also had encouragement from such Friends as I think are able to judge for us.
I remember my former buffeting, and He who knew, and now knows,
the integrity of my heart, was, is, and I hope will be, my Helper and your Helper.
May your spirit feel and travail with ours,
that so when we rejoice you may rejoice also.

--

From Falmouth we went to Penzance and lodged at William Prideaux`'s,
where we stayed till the 28th;
from there we came to Redruth and lodged at William Phillip`'s,
whose wife and I had formerly been acquainted,
and before we parted we were favoured with a renewal of that love that changes not.
And oh, did we but keep near enough to it, what useful vessels would we be!

On the 30th we came to Edward Fox`'s at Wade`'s bridge;
had a meeting next day at Port Isaac; were at Liskeard on first-day,
and had a very large and satisfactory meeting.
In the evening were at Looe, and at the Quarterly Meeting,
which lasted two days. Some things were very trying, but the Truth was over all,
and we were well satisfied with being there.
From there we went to Plymouth to their Quarterly Meeting, which ended on sixth-day--
a very satisfactory time.
We were comforted in the parting meeting,
and in much love and nearness of spirit took leave of the few who are alive in the Truth.
Then we proceeded to Kingsbridge and attended their meetings on first-day,
which were very dull and painful. But we found a little liberty by visiting some Friends,
and were helped to do our duty and came away with peace.
We were at Exeter on the 12th, and attended their fifth-day meeting,
which was a very comfortable opportunity to such
as are truly waiting for the consolation of Israel.
From there we came to Uffcolme, and were at their meeting on first-day.

On second-day, accompanied by several Friends, we went a very long journey to Whitsby,
near Torrington, and lodged at Thomas Millard`'s; the next day were at Littland,
and had a meeting in the house of a Friend, whose family was large but very disagreeable.
And although I was an entire stranger, yet He who reveals His secrets to His children
gave me a sense of these unhappy people,
and by His help we testified against all uncleanness;
and I desired Friends not to hold their meetings in that place, for it was not reputable.
There were a few present who did not profess with us, which I was glad of,
that they might bear witness to the truth of what was declared in that meeting.
We went back to Thomas Millard`'s, and had a meeting in his family,
he having nine children.
We also had the company of Nathaniel Williams and Ann Dymond of Exeter, with others,
and I believe the Truth was declared,
and we had a sweet reward for our labour and long travel,
it being the hardest journey I have had since leaving home.

We returned to Uffcolme, and on the 25th were at the meeting at Spison;
from there to Wellington and Milverton, lodging at Thomas Pole`'s,
and were at their meeting. But oh, what a cloudy time it was!
Several Friends, however, dined at our lodgings,
where we had a satisfactory and comfortable season,
and returned in great peace to Spison, being at their meeting on fifth-day.
From there we went to Ilminster, and were at their meeting to satisfaction.
Then to Chard, a large meeting, but very few Friends in the place.
Next to Cloakham to the widow Canaway`'s, where we dined,
and had a very good and satisfactory season with three widows,
one of whom was above eighty years of age, but alive in the Truth.
From there we proceeded to Bridport, and had a satisfactory meeting on third-day evening,
though I was very unwell.

On sixth-day we had a satisfactory meeting at Poole;
from there by Ashmore and Shaftsbury to Sherborne, and had a laborious time. Indeed,
we had painful labour in most places, because of the prevalence of a worldly spirit.
Next to Compton, to our worthy friend Jonah Thompson`'s;
from there to Yeovil and Puddimore, where in an evening meeting we were much comforted,
being owned of our heavenly Father, whose glory shone forth among us,
and His power was over all the worldly spirits.

On fifth-day we had a meeting at Long Sutton; from there to Summerton and Street;
at the latter place, attended the funeral of Mary the wife of James Cloather,
where was our worthy, aged friend Jonah Thompson.
Here I parted with my near and dear friend and companion, Ann Byrd,
and went to Glastonbury. We lodged at William Metford`'s,
and had a satisfactory meeting at that town on seventh-day;
from there we went with John Thomas to his house.

On first-day we were at their meetings at Sidcot, where we were again refreshed together,
though among a poor company.
I then went to Yatton and lodged at Lydia Harewood`'s, a very kind Friend.
We paid an agreeable visit to John Hipsley`'s, and had a profitable opportunity.
On the 18th I had a meeting at Clareham.
I was now in great distress, not having heard from my dear husband for many weeks,
so that I sunk exceedingly low and had great conflict of soul.
Yet as my heavenly Father knew that my heart was sincere, He,
in His customary goodness and tender mercy, arose for my help,
and enabled me to rejoice with the few who truly feared Him.
From the meeting I went to dine with several Friends at the widow Wilmett`'s,
a young woman left with seven children, and then returned to Yatton,
and on the 19th had a meeting at Hollowtree. From there I went to Pensford,
and was accompanied by Robert Peters to his house in Bristol.

In this city I remained several weeks, and duly attended meetings,
there being three on first-day and three on other days of the week.
I think I only appeared twice in testimony and three or four times in supplication;
yet having done all that was required, my soul had peace.
But the deep travail I passed through no tongue can express.
Oh, the deep baptisms and many bitter cups that are
handed to the living children! And doubtless they are good for them.
If we do not suffer with Christ, we shall never reign with Him.footnote:[2 Timothy 2:12]
And as He, who indeed was and is the Son of God,
was made a gazing-stock and called Beelzebub by some,
why should any of His servants be unwilling to bear reproach,
or to sit like fools in silence?
O, how do I beg to be preserved from ever moving in my own will;
I had rather bear the name of a dumb prophet.
I am sensible that these stripping seasons have been very teaching to me;
and when we look like fools to those who are foolish indeed, we learn true wisdom;
for in true silence we have the best teaching, even the Lord Himself is our instructer.
O that we, as a people beloved of God, were but truly obedient to His law;
then we should be far from being weary of true silence,
but would rejoice to be favoured with it. For when our minds are thus gathered to God,
in pure stillness and nothingness of self, the tempter has no place; he hates quietude,
and I am glad that I have been helped to starve that restless spirit,
and been made an example of silence.
I was engaged to sit silent eleven or twelve meetings one after another,
in and near Bristol, and can look back with satisfaction.

I left Bristol on the 18th of ninth month, and came with many Friends to Gloucester,
where was held the circular meeting--a very large
gathering of Friends and great numbers of other people,
who behaved very soberly.
The meetings were well conducted and greatly favoured,
and many were made thankful to Him who is the Author of all good;
for His great name was glorified, who is alone worthy.
Amen.

I now proceeded to Colebrook-dale, and lodged at the house of Richard Reynolds;
his wife being my former acquaintance, I felt drawn to pay her a visit,
and we were glad of each other`'s company.
I was engaged to stay longer than I intended, and having been so long from home,
it was indeed very trying. But my dear friend Rebecca Reynolds
was as a nursing mother unto me,
and I was glad that I gave up to attend their Monthly Meeting, which was held at New Dale,
28th of ninth month. And though few are willing to attend such meetings,
yet those who are were encouraged--the power of God was manifested, and the living,
faithful children were comforted.
I parted in true love with my friend, and came with John Young to Birmingham;
from there I went to Coventry where I was very kindly received,
but it was a cloudy suffering time at both meetings.
I was very unwell and exceedingly low, but got safe to Leicester the 4th of tenth month,
where, contrary to my own inclination, I felt engaged to stay for their Monthly Meeting.
But oh, such dullness and indifference appeared that
I cannot express the feelings of my distressed mind,
so that I went home in much fear, where I arrived safely on the 6th of tenth month,
and found my husband and son well, for which I was thankful.

I have been much at home from the twelfth month, 1773, to the fourth month, 1774.
My husband and I were at the Quarterly and general meetings at Nottingham,
as well as at Breack, and at Ruddington the 1st of fifth month. I was at our Monthly Meeting,
and visited one who had married out of the Society,
and had brought upon herself shame and confusion.
Our visit was, I believe, very satisfactory,
and I was well pleased that I had attended these several meetings.
I was also at Womswold, and in the sixth month at our Quarterly Meeting;
from there to Coventry, Oakham, Lincoln, Blyth, Chesterfield, York and Sheffield,
so to Mansfield, Nottingham, etc., and had many satisfactory meetings.
In the seventh month I was at Loughborough, Atherstone and Leamington,
and at the general meeting at Monyash.
In the ninth month I was at our Quarterly Meeting at Leicester,
where was Sarah Gurney from Norwich, who had a good opportunity,
and a very satisfactory meeting it was.

[.small-break]
'''

+++[+++In this year she was again from home, as appears by the following letter:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Leicester, Twelfth month 16th, 1774.

[.salutation]
Dear Husband,

I know you will be pleased to hear well of me:--indeed,
very closely have I been tried of late. Bitter have been my conflicts,
and heavy my exercise, unknown to most, and in fear that I should become a castaway.
Oh, how long have I sought for Him whom my soul loved! Yes, I sought and found Him not,
until at length He who is the Messenger of the covenant did come again into His temple.
I went to meeting, where were honest William Dodgson and his wife, and sat by them.
Oh, how my poor soul was humbled!
The hardness that I had long groaned under was removed--"`the mountains gave way and
the hills trembled;`" Jordan also was driven back at the presence of the mighty God,
whose power filled His temple, and I again rejoiced in His salvation,
beholding the glory of His house, and admiring the attendance of His servants,
and the beauty of that work which is carried on without the noise of a tool.
All this was in pure silence.
It was indeed a solemn feast to me,
and I believe that Divine good overshadowed the whole.
And while we sat there as in a heavenly place, George Boone came in, who,
after a time of continued silence, had an acceptable opportunity,
and the meeting seemed to end well.

--
