== Chapter VIII

[.chapter-synopsis]
* Her visit to Bristol, Wellington, Exeter, etc.

On the 6th of ninth month, 1784,
I received a few lines of approbation from our Monthly Meeting,
having the weight of a journey upon me.
And although I could not see my way clearly any farther than Shipston,
yet I did not believe that I would return home soon,
and so took a very humbling farewell of my near and dear connections,
and was accompanied by my husband to Leicester.
On the 9th, our friend Daniel Woodland went with me to Hinckley;
from there to Coventry, Warwick, and Shipston,
where were many Friends whom I was glad to see, among them my dear companion,
Ann Byrd.
The meetings were very large, both of Friends and others;
many public Friends were there from various parts, and Patience Brayton from America.
The concluding meeting was much to the satisfaction of many.

My way seemed now open towards Bristol, and having Ann Byrd for my companion,
I went on pretty cheerfully.
We were at several meetings on our way to Bristol,
and were at theirs on first and third-days,
and at the Select and Quarterly Meetings on fourth-day.
From here we proceeded to Sidcot, and had a favoured opportunity; from there to Bridgewater,
Wellington, Uffcolme, and on first-day to the Monthly Meeting at Collumpton;
in the evening got to Exeter.

[.offset]
+++[+++Here she wrote the following to her husband and children.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Exeter, Tenth month, 1784.

I do not remember ever setting out with so little sight,
nor can I express what I felt before I left home, but think my exercise was in part felt,
and also seen, by you, my dear husband, and that you, with myself,
do believe I moved at the right time.
A way has indeed been opened, and help administered in a wonderful manner,
very unexpectedly to me;
my deep sufferings at home have brought me into such a degree of willingness,
that I endeavour to follow my Lord wherever He leads me,
and to discharge my duty faithfully in every place where my lot is cast.
I was glad of the company of M. L. and A. C. at Shipston.
There I also met my dear companion Ann Byrd,
and we are very nearly united in true Gospel labour.
We attended their week-day meeting at Cirencester,
which was to our friends`' satisfaction, and at several places in our passing along,
we were favoured with the manifestation of our heavenly Father`'s love and regard,
both to us and to those we called upon.
We attended their Quarterly Meeting at Bristol,
and I saw many Friends who remembered my being in the west before,
and we were truly glad to see each other.
But at most of the meetings I was shut up,
hearing a voice within me saying, "`you must come here again,`" and so I believe I must.
I felt drawn towards Kingsbridge,
where the Quarterly Meeting for Devonshire was held
on the fourth-day following that at Bristol.
I had never more cause to be thankful than I have now,
it being such a time of favour as will by some be thankfully remembered.
Oh, my dears, all of you, feel and rejoice with me,
for sweet is the peace that dwells in my soul!
Strong are my desires for you, as for my poor self,
that a steady perseverance and preservation from all evil may be witnessed by us.
You are all often in my thoughts,
and in the best love I dearly salute you my dear husband,
with my children and children`'s children.

--

On second-day we reached Kingsbridge, a very long journey, which, I believe,
would have been too hard for me had not our dear friend Mary Ware of Wellington
taken me in her carriage.
Indeed, the kindness of Friends to me is very great.
On third-day was a large meeting,
and on fourth-day the Quarterly Meeting--both very favoured and comfortable seasons,
more so to me than at any place where I have been since leaving home,
so that I was thankful I was there. Many Friends, too,
who remembered my former visit to them, rejoiced to see me once more,
and in a renewal of that love that is unchangeable,
we took a final farewell of each other.
On the 30th we came back to Exeter, and stayed over first-day.
On second-day to Uffcolme, where I stayed until seventh-day,
only visiting one worthy Friend, Robert Fry, who has been in great affliction many years.

On first-day we were at meeting at Milverton.
The next day went to Minehead, to visit Robert Davis,
he being very ill and not likely to recover; he has a wife and several hopeful children,
with whom we had a comfortable opportunity.
On fourth-day morning, after a very agreeable and heart-melting season,
we left Milverton for Wellington, where we visited several families,
and were at meetings on first-day. It was a trying time to me,
but I was helped to discharge my duty, partly in testimony, but mostly in silence.
On second-day returned to Uffcolme, where I again remained awhile,
it being my dear companion`'s habitation.
On fifth and first-days were at meetings at Spiceland, about a mile from Uffcolme;
the latter was very large, many Friends from other meetings being there.
The next first-day I was at meeting at Wellington, and so much favoured in the forenoon,
that I think I may say, as was said formerly, the Truth was over all.
I stayed more than a week in this place,
my health for a time being in so dangerous a condition
that I was ready to conclude my time in this world was nearly over;
but through Divine mercy I recovered.

[.offset]
+++[+++At this place she again wrote to her husband and children.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Wellington, 1st of Eleventh month, 1784.

How thankful shall I be to hear of the welfare of
you all both in things natural and Divine;
and the way for us to enjoy temporal blessings with contentment is
to be chiefly concerned to witness improvement in things that are heavenly,
an increase of such riches as will never decay,
and a being clothed with a garment which will not wax old.
You well understand what I say; and as we are blessed with a knowledge of these things,
our happiness consists in doing them.
I wish my dear children may take good heed that their
conduct in every respect may be truly teaching,
and your conversation so savoury as to season the tender minds of your dear offspring,
and that you endeavour to keep them in subjection,
so that if I be favoured to see you again
I may find you so comfortable as to cause rejoicing,
as was the case when I returned from Ireland.
I beg you will not slacken your pace nor allow anything
to hinder you in your progress heavenward.
Oh, how does my poor soul travail for you even as for myself,
and I can thankfully say that the Lord has been my helper hitherto,
and believing I am in the way of my duty, I have the reward of peace.

--

Being again joined by my dear companion, who had a concern,
and the approbation of her friends, to visit Bristol, we took leave of my kind friends,
to whom I was nearly united.
We were at meeting at Taunton; from there to Bridgewater,
and lodged at our worthy friend Joseph Ball`'s,
who accompanied us to John Hipsley`'s near Claverham. We attended their meeting,
and afterwards had an opportunity in our friend`'s family;
he had been long confined with illness,
and we felt near sympathy with him in his affliction.

On sixth-day were at Sidcot meeting; then to Bristol, and lodged with Mary Peters.
Our stay in this city was very long, a full nine weeks, in which time like good soldiers
we endured much hardship, being greatly afflicted both in body and mind.
When able, we duly attended their meetings and visited many families.
We were favoured with many satisfactory opportunities,
and though mostly silent in meetings, yet can with humble confidence say,
that I was not guilty of any omission in all this long travail.
"`Oh,`" says my soul, "`that there may be more life and fewer words among us.`"

[.offset]
+++[+++The lively interest which she felt for the spiritual welfare of her son,
is set forth in this parental appeal:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Son.

[.signed-section-context-open]
Bristol, Twelfth month, 1784.

I received your welcome letter nearly two weeks ago
and was glad to see your handwriting,
and the more you feel of my continued love and regard for you,
the more yours will increase; and your obedience to us, your dear parents,
will still be manifested,
and you will feel strength renewed to maintain a
holy warfare against the unwearied enemy.
You, my dear child, well know that if there be no warfare there will be no victory,
and as the flesh will war against the Spirit,
so I hope you will be favoured with the pure Spirit
of Truth to enable you to war against the flesh.
Do not let go of your hold, cease not to strive,
and I have no doubt but that you will obtain the victory.
The love of Truth having seemed to spread in my soul
towards many of my friends in this city,
we have entered into the arduous labour of visiting families.
I do not see at present that we shall visit all that profess with us,
but have been to visit several with whom I was before acquainted,
and we have had fresh visitations in most places.
On account of the shortness of the days, and my being unable to walk, we get on slowly;
but as we step safely, we feel satisfied that we are where we ought to be.
I beg for patience, remembering that the end will come when all our labours will cease,
and the prospect of a happy conclusion is at times very comfortable,
and by me rather desirable that it may soon be experienced.

--

On the 17th of first month, 1785, we left Bristol,
having the blessed reward of pure peace for our labours.
Lydia Hawksworth accompanied us to Frenchay, where we had a meeting.
Several Friends from the city were there, and we were acknowledged by our great Lord;
His name was magnified, and His own works did praise Him.

Early the following morning, accompanied by Thomas Scantlebury, we went to Painswick,
and were at their meeting on the 19th, and at Tewkesbury on the 21st.

On seventh-day we reached Worcester, and lodged at our kind friend Timothy Bevington`'s.
Were at their meetings on first-day, where were Patience Brayton and her companion also.
On second-day, the 24th, my dear companion left me, she being very desirous to get home;
but I was not easy to leave Worcester so soon, and stayed more than a week longer,
in which time I visited several of my acquaintances, had several satisfactory seasons,
and was much favoured at some of their public meetings,
so that I came away with sweet peace.

On fourth-day morning I took an affectionate farewell of my dear friends,
and was accompanied by George Beckett and Mary Bewley to Alcester, where they left me,
and I lodged at the widow Stanley`'s,
from which place I was favoured with the company of an agreeable young woman, Mary Ford,
to Jeffery Bevington`'s, at Eddington.
I was at their meeting on fifth-day, and at the meeting at Ormscott on sixth,
but the weather being severe, there were few Friends present;
yet it was a time of deep travail and hard labour for the honest-hearted.
On fourth-day I was at the meeting at Warwick, and on the following day reached Coventry,
where I was joined by my husband.
Attended their meeting on first-day, Timothy Bevington of Worcester being there also,
and we were acknowledged by the presence of our Great Master, and employed in His service.
On the 15th of second month we got safely home, and found our dear children well.
I had been absent on this occasion more than five months.

[.asterism]
'''

+++[+++From her memorandums which come down to the fifth month, 1801,
this journey appears to be the last which she performed
with a certificate from her Monthly Meeting.
Nevertheless, she was almost continually engaged in the service of Truth,
in attending meetings in various places, and often through much bodily infirmity,
in the course of which her remarks are frequently weighty and edifying,
of which the following are a few:]

On the 17th of seventh month, 1735, I being very infirm and now at home,
and having been often engaged in my good Master`'s service, and having a sure evidence
--even the Truth bearing me witness that I am in the way of my duty to my great Lord--
my spirits are borne up over all opposers and such as say hard things of me,
and I have peace.

+++[+++In 1787, she writes from London to her children,
showing the unabated affectionate concern for their everlasting welfare:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Children.

[.signed-section-context-open]
London, Sixth month, 1787.

O my dear children, endeavour to keep near to that preserving Power,
who is alone able to help and strengthen you to persevere in the way of life and salvation,
and also to teach you how to order your dear little ones.
Often does my spirit breathe unto the God and Father of all our mercies for your help,
that nothing may draw you aside from that pure path
in which I know you have enjoyed true peace.
Friends seem glad to see us.
The meetings are very large,
and graciously owned by Him who is the crown and diadem of our assemblies.
Happy would we be if all kept to the proper standard,
and never moved out of the pure order of the Gospel.

--

[.offset]
+++[+++On the 26th of eighth month, 1788, she writes:]

I left my home,
having for some time felt an inclination to visit a few meetings in Warwickshire,
and Ann Byrd coming our way and being very desirous of my company,
having a concern to visit the said meetings, we went together in true unity,
and were indeed fellow-labourers in the Gospel, though very deep was our travail,
and great the exercise of our minds,
because of the lukewarmness and indifferency which
prevail among a people who have been so favoured.
Yes, these were a people beloved of God and chosen
of Him before all the families of the earth;
so that surely, if there is not a reformation, they will be punished by Him.
How are they visited, and how do some labour for their restoration;
and though much tried, we were at times much favoured and enabled to discharge our duty,
for which we enjoyed peace; the faithful among us were comforted,
and the Lord over all was magnified, who alone is worthy.

I accompanied my friend as far as Worcester, where we stayed more than a week,
and visited several aged people much to our satisfaction.
At this place we parted, and I came to Chadwick,
where we had a large and satisfactory meeting, and after
attending the meetings at Dudley, Birmingham and Coventry,
I returned home in peace the 21st of ninth month, 1788.

At the latter end of the fourth month, 1789,
I attended our Quarterly Meeting at Nottingham.
Several strangers were there, and I had satisfaction in being with them,
being favoured with a sense of Divine life, whereby I had access to the throne of grace,
and witnessed a renewal of strength in the inner man,
although I feel a great decay of bodily strength,
and was ill part of the time I was there.

In the fourth month, 1792, I again was at our Quarterly Meeting,
and in the several sittings thereof we were favoured
with a sense of the love of our Lord,
who still is with those that are gathered together in His name.

Fourth month 29th, 1793.
Attended our Quarterly Meeting at Nottingham,
and 1st of fifth month our Monthly Meeting at Loughborough.
This little journey I was enabled to perform beyond expectation,
and felt my mind under the covering of the Spirit of the Lord, and returned in peace.
My physical complaints not feeling so grievous as in months past,
I apprehended it my duty to attend some Quarterly Meetings,
but being still in a very weak state, the trial was great.
On the 15th of sixth month, I left home, accompanied by my son Joseph,
and reached Coventry that evening. Attended three meetings on first-day,
and the Quarterly Meeting on second.

Went to Warwick on third-day, was at their week-day meeting on fourth,
and at Eddington meeting on sixth-day. At Shipston meeting on first-day,
and to Banbury that evening; was at three meetings on second-day,
and the Quarterly Meeting on third. I went the same day to Buckingham,
was at meeting in the evening, and at the Quarterly Meeting on fourth-day,
which was large and satisfactory.
From there to Northampton;
on fifth-day was at meeting in the evening, and at the Quarterly Meeting on sixth-day;
from there to Wellington that evening,
and lodged at our very kind and honest friend Benjamin Middleton`'s.
Was at Finedon on first-day,
at their Monthly Meeting on second, and on third-day to Ridlington Park.
From there to Oakham, at their meeting on fifth-day, and on sixth,
after having a solemn opportunity with our dear friends there, returned to the Park,
and on seventh-day, in a renewed sense of Divine love, we took leave.
On first-day was at their meetings at Leicester; from there to Groby Lodge;
on fourth-day returned to Leicester,
it having rested on my mind to be there the first-day following.
I became very ill at meeting, and lodged at John Priestman`'s,
whose wife took great care of me. And getting better,
I was able to sit meetings on first-day,
and was well satisfied that I did right in staying.
On second-day I reached home in safety, with the richest reward,
for which I beg to be truly thankful,
and desire that I may be carried safely through this life of trouble into everlasting rest.

I have thus had one more opportunity, though unexpectedly, to renew my acquaintances
and strengthen the bond of pure affection which we in years past had known,
having at these four Quarterly Meetings, as well as at some others,
fallen in and met with many of my dear friends, whom I was truly glad to see,
and probably took a final farewell of,
I being now in the seventy-sixth year of my age, and infirm.
The succeeding two years I was engaged in attending many meetings near home
to satisfaction.

[.offset]
+++[+++In the year 1794, she writes to her family from Leeds:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband and Children.

[.signed-section-context-open]
Leeds, Ninth month, 1794.

My absence from you has been longer than I had any sight of when I left you,
but at times I have been made to believe
that as I did so in pure obedience to the Divine command,
so I still continue bound to the law and the testimony; yes,
to that pure law that the Lord writes in our hearts.
But as I am led in a way that I knew not of, so I could not inform my friends thereof,
nor have their approbation;
yet I endeavour to take heed that I make no breach in good order,
and I seem to have a very kind welcome wherever I have yet come.
Nevertheless, great have been the trials of my poor mind,
and the exercise thereof inexpressible;
and though I consider my coming here as a friendly visit,
yet if I did not feel a necessity to come, surely I would not venture to do so.
With humble thankfulness I have been made to admire how way is made for me,
so poor and unworthy a creature as I am.
I feel an inclination to be at the Quarterly Meeting at York,
and am favoured with the agreeable company of our
dear friend M. S., wife of William Smith,
of Doncaster.
I long to hear of the welfare of you all, and if my prayers might avail,
they are very frequent on your account.
Oh my dears, forget not to be watchful! You know how uncertain time is,
and what a sad thing it is to be unprepared;
may I not say our happiness consists in doing the will of God,
and in living in obedience according to knowledge?

--

On the 8th of fifth month, 1795, attended the Yearly Meeting in London,
where I was kindly received by my friends at my good old quarters, the widow Roe`'s.
This journey I bore better than I expected,
and was enabled to attend most of the meetings; and like one raised from death unto life,
I was made to testify of the Lord`'s goodness,
and to speak well of His great and powerful name,
which is still manifested in the assemblies of His people,
so that we can say our God is glorious in holiness,
fearful in praises, and does great wonders among us.
Great is the reward and sweet is the peace that my soul now enjoys. This bears me up,
though I move with a poor afflicted body, and in advanced age,
and being unable to walk from one meeting to another,
it is with gratitude I mention the kindness of my friends in assisting me in many respects.
In their thus helping a poor disciple, they will no doubt receive a reward,
even a portion of that peace which my soul now enjoys--
peace with God and rest in Him who has dealt bountifully with me.
Amen!

[.offset]
+++[+++In the eighty-sixth year of her age,
she penned this short outpouring of parental affection towards her grandchildren:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Grandchildren.

[.signed-section-context-open]
Donnington, Third month, 1804.

Being likely to soon depart, I have been set down as in the depth of poverty;
but I felt willing to salute my dear grandchildren once more.
And though it will expose my weakness, yet it will manifest my willingness,
and that you are very frequently in my remembrance.
I am glad that you are so agreeably placed, and wish you to improve in the best things,
as it seems you are encouraged to do both by word and example.
However, take heed to the gift that is in you,
whereby you may be made truly wise and fitted for
whatever service you may be employed in;
and thus being faithful in a little you will be made rulers over more,
and have the joyful sentence at last of,
'`come you blessed of My Father, enter into the joy of your Lord,
and into your Master`'s rest.`' Now, having thus written a little of my meaning,
and the fervent desire of my heart, I conclude in that love which changes not,
and am your very aged, infirm, and much reduced grandmother,

[.signed-section-signature]
Ruth Follows.

--
