== Chapter II

Her visit to the meetings of Friends Westward--to Bristol--and thence to London.

On the 28th of second month, 1760, after a long time of deep exercise,
I parted from my dear children,
having the approbation of my friends and a certificate according to good order,
to visit the meetings of Friends westward to Bristol, and from thence to London;
my dear husband accompanied me a few days, first to Leicester then to Coventry;
at which places I held no meetings, but parted with my friends in much love,
being engaged in my mind to be at Birmingham on first-day.
I was at their meetings to my satisfaction.
On the next day I parted with my dear husband, which was no small trial to me,
being left alone and never having gone such a journey by myself,
it seemed full hard for me to bear; but I found it best to be still,
knowing that I was engaged by and for Him,
who is alone able to help and preserve his people.

From Birmingham I was at various places, attending nineteen meetings,
and on the 20th of third month reached Bristol,
where I attended six meetings before the quarterly meeting, and seven afterwards.
I now seemed to take my farewell of them to my satisfaction,
though I was an example of silence in many of their meetings.

I here feel inclined to look back upon my journey,
not having had an opportunity until now to make any remarks.
And first I find freedom to say,
for the encouragement of such as have the right cause at heart,
that I have had no cause to repent leaving home and my near and dear connections there;
for the Lord has been pleased to be with me hitherto.
I have been kindly received by Friends; and at this time a hope is afforded me,
that I shall be enabled to perform the rest of my journey;
and being well assured that I am in the way of my duty, I am thankfully content.
I was now favoured with the company of Mary Winter, a young woman,
young also in the ministry; she was with me at Bewdley and Bromsgrove,
and I was truly glad of her company.

I was favoured also with the company of Martha Merrill,
who stayed with me whilst I was at Bristol, and accompanied me to Frenchay and Earthcot;
at the latter place we parted in much love.
On seventh-day I went to Bath and lodged at Love Tyler`'s, who very kindly received me,
which made my lonesome situation much pleasanter whilst I remained in that town.
My great Master too,
whose servant I have been and for whom I desire that I may ever be rightly engaged,
was pleased to send my dear friends Robert and Love Peters,
from Bristol to Bath on first-day morning.
O, how glad was I to see them,
for it seemed as if I could hardly live or be able to get that day over;
but being thus favoured with agreeable company,
and again finding the Lord to be my helper,
I got through the meetings with some degree of satisfaction.
My dear friend Love Peters, offered to accompany me to some meetings,
which I very thankfully accepted;
we were at nine including the Quarterly Meeting at Cain, where we parted,
she returning with her husband, who came from Bristol for her.
There were many Friends at the above meeting from several places,
but too few who were truly concerned for the cause of God;
so that they who were rightly engaged had very hard work;
but the power of the Most High was over all, and his great name was glorified.

We next proceeded to Devizes, and how hard did it seem to me to go amongst strangers.
I cannot express what my soul went through in that place;
I had nothing to say at meeting; neither could I see for some time how I might find ease.
I endeavoured to be still,
and cried unto the Lord in my spirit that I might be preserved,
and if it would please him to show me what he required of me,
I thought I should submit if it were ever so hard to my own will.
As thus I sat, there came several to dine at the house where I was.
We sat down to dinner, and in the bitterness of my soul did I at the command of the Lord,
pour forth my supplication unto him for their sakes, poor souls,
who were living in forgetfulness of God: yet did the Lord visit them in this wise,
and engaged me to pray for them; and by my obedience I had peace.
O! how thankful was I that I could leave the town with satisfaction;
so from Devizes I went to Marlborough,
though still in dread and fear lest I should not be able to stand my ground;
but blessed be the Lord who has thus been pleased to lead me,
even as through the valley of the shadow of death; he stood by me,
and I got safe from the town.
From thence to Newberry and Backhurst, and Reading: stayed their Half-year`'s Meeting,
with which I was well satisfied; there were many worthy Friends present,
one of whom was Joseph White, from America.

I then proceeded towards London, where, and in its neighbourhood,
I continued nearly six weeks visiting the different meetings.
Finding myself at liberty when the Yearly Meeting was over
I parted from many Friends in much love and satisfaction,
some of whom I had now first become acquainted with;
amongst these was Susannah Hatton from Ireland, a widow,
who was intending to visit America, and had left six children.
My friend Anne Wright, was nearly two weeks at John Cartledge`'s in Wood street,
and we were together at several families, to much satisfaction.
May that love ever remain with them in which we were truly united;
and although we may be outwardly separated,
yet we are as epistles written in one another`'s minds.
--Oh! that we may keep near to the Fountain of love and life! then we
shall have to rejoice together in the communion of the one pure Spirit,
which is extended to the whole family of God, the world over.
Amen.

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Husband.

[.signed-section-context-open]
London, Fourth month, 25th, 1760.

I am still satisfied that I am about my Father`'s business,
and for thy comfort may inform thee that I now enjoy peace,
and desire that we may be enabled to do our duty to Him from whom all our blessings come.
I was at Gracechurch street meeting this day, and came away in peace;
Isaac Sharpless was there in the morning, and we were comforted together.
His concern has been to visit families,
and he has got through so far as to think he will be at liberty to go home tomorrow,
having been at many places and families, although only here a little more than a week.
By his labour he has made way for others who had the concern,
but perhaps could not so well begin that great work.
In looking back a little to my visit at Bristol,
the place where I have often been concerned,
it was not without a cause that my service there should be in a manner I did not expect.
I laboured diligently and was baptized often, because of the sins of the people,
and brought near to the mourners in Zion, and feel as I now write,
my spirit drawn towards them.
It is pleasant to me to think of them,
for we were joined in a holy fellowship which will endure.
I visited many families,
in which engagement I had freedom to join Martha Merrill and Love Peters.
I had to admire how their states were brought before me; nay,
I had hard work to believe my Lord, but his mighty power did enable me to do his will,
for which I am truly thankful; and the love of God did so prevail that many were bowed,
and seemed to be brought near to us.
Although I have been thus favoured, yet fear and weakness encompass me,
so that at times I am ready to faint and seem like one who has not known good.
Oh! may the fear of the Lord, which is a fountain of life,
ever preserve us from the snares of death.
May we who have known redemption in some degree,
never more be entangled with the yoke of bondage.
May we be favoured with food and raiment,
and a blessing upon our tender offspring from the Holy Spirit,
which hath and doth conduct us; and may this good Spirit rest upon our children.
This I desire for them and us more than uncertain riches, which will fade away.
My mind is very closely engaged, often in great painfulness and watchings,
lest the enemy, who way-lays me daily,
should so prevail as to cause me to do any thing
that would occasion the honest-minded to be uneasy.
Oh! the proving seasons I have met with, but which I hope are all for my good;
and I do expect many in this place, and surely thou with my dear friends,
will have a concern to pray for me.

--

On 4th of sixth month I left London, and went with our friend John Griffith,
to his house at Chelmsford; stayed their first-day meeting,
where I was again favoured with the company of Susannah Hatton.
With these Friends I proceeded to the Yearly Meeting at Colchester,
after which we again parted, and on the next first-day I was at Ipswich;
thence to Woodbridge Yearly Meeting, and on the 18th to Yarmouth; next to Norwich,
where I lodged at Samuel Gurney`'s, and was at many meetings with many worthy Friends.
Then in company with Mary Gurney, I went to North Walsham;
from which place my worthy friend John Ransom went with me to several meetings.
I was truly glad of his company, and hope I may not forget his kindness to me.

We returned to Norwich 12th of seventh month,
where I mostly continued till 7th of the ninth,
when I parted with my dear friend with whom I had been so unexpectedly detained.
It was very contrary to my own will, and might seem strange to many;
but I believe it was according to the will of God;
and for his cause did I mourn with them that mourned, yea, I was very often in sorrow;
a time of deep searching of heart it was to me; but blessed be the Lord,
he was pleased after he had thus tried me,
and found me in sincerity truly desiring that I might not be deceived,
but that his will might be done--I say, after all this time of proving,
he let me see my way again; and when the cloud was removed from my tabernacle,
I went on my way rejoicing.
My friend John Lucas, accompanied me until I came to Lynn;
thence I went to Downham to their general meeting,
where I met David Coulson and William Dodson.
Proceeding to several places I came to Godmanchester, where was Samuel Spavold;
afterwards I proceeded homeward, and arrived there the 15th of ninth month, 1760.

+++[+++The following letter is a further description of the close
conflict she endured in being detained at Norwich:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Norwich, Eighth month 18th, 1760.

It seems very hard for me to tell thee that I am yet bound in this place,
although when I wrote to thee I thought that I might have got away.
It is not omission of duty that detains me,
but surely it is for a trial of my patience and of thine, for a cause we know not.
I fear we have been over anxious;
yet sometimes I have hopes that thou art more resigned
to the will of the Most High than I am.
If I be rightly sensible, I believe that I am where I ought to be;
and although I would have hid the concern, yet I could not;
for several Friends whose spirits are united with mine,
and who had a sense of my travail of soul came to see me--and my dear friends
with whom I make this long abode told me they did believe I was not clear,
and my unwillingness to stay made my affliction heavier; which indeed was true.
Friends are very kind and loving to me,
seem glad to see me and tell me they are not weary of me.
When I consider how it was formerly,
when our worthy ancients were concerned to speak in the name of the Lord,
how they were haled to prisons, abused, and all they had taken from them; yea,
that many sealed their testimony with their blood; when I remember those things,
what can I say?
There hardly seems room for us to complain;
our trials seem so trifling to those which they met with;
and looking at what many are tried with now, as to going over sea,
oh! my heart is often affected for them.
Yet how unwilling I am to be thus confined in my native land,
which seems but little to engage with to what those have who cross the mighty ocean.
Therefore, as it thus happens for me to be tried on this wise,
I beg that thou may still resign me;
how affecting would it be to us both to bring a burden home with me.
O that it may not be so! it would be better for thee to see me no more,
than to see me in that anxiety of soul which disobedience brings.
Therefore be thou comforted,
for although thou may with me have been tossed as with a tempest,
yet our foundation is sure, against which the gates of hell shall never prevail;
and may we ever remain upon it.

--

30th of seventh month,
1761--Although I have not set any thing down of my travels for many months,
yet I have not been much idle,
but have had an afflicting time so that I could not go far from home, yet when able,
got to our own Quarterly Meetings.
In the sixth month, Joseph White from America, was at our meeting,
and I with other Friends,
were with him at Soilby and Dalby.--In the seventh month my husband took me to Nottingham,
I being engaged for Lincoln Quarterly Meeting, where were John Griffith, John Hunt,
Thomas Corbin, Joseph Taylor and Joseph Roe,
on an appointment from the Yearly Meeting to visit the Monthly and Quarterly
Meetings in divers counties--whose company was very acceptable.
After my return home, I attended the Atherstone general meeting.
