== Chapter IV

Her visit to the meetings of Friends Westward, and in Wales, etc.

On the 17th of third month, 1763,
it having been my concern for some time to visit the meetings of Friends Westward,
and having the concurrence of my friends and a certificate from the Monthly Meeting,
I proceeded accordingly, attending the Quarterly Meetings at Leicester and Birmingham:
we had the company of Catherine Payton, who had good service.
I was afterwards at Dudley, Stourbridge, Bromsgrove and Worcester;
at the latter place I remained until the 7th of fourth month,
visiting several sick Friends and attending their meetings for worship,
also the Monthly Meeting,
where I should have been glad if more of the women Friends had attended; however,
I think I may say we were favoured with the love of our God,
not only in the meeting for discipline but in that for worship,
and enabled to offer thanksgiving and praise to his most holy name,
who is alone worthy thereof.

From Worcester I departed in much peace, accompanied by several Friends to Tewkesbury,
where we had a suffering meeting;
thence to Bristol and arrived at my dear friend Robert Peters,
whose wife though in a very poor state of health, accompanied me to most of the meetings.
On the 20th was at Frenchay, in their company, where at meeting, we had some satisfaction.
Robert Peters returned home, but his wife accompanied me to Earthcote meeting,
where we were favoured with strength to labour amongst
a people who are not enough concerned for themselves.

We returned to Bristol on the 22nd, where I remained until the Yearly Meeting,
at which we had the company of John Hunt from London, and Isaac Sharpies from Hitchin,
who were engaged to labour and travail, and to speak to the states of the people.

Bristol, Fourth month 30th, 1763.

Though I am far from being lifted up,
yet I esteem it a great favour that I have hitherto been preserved from sinking too low;
therefore I hope thou wilt continue easy about me; for though I am thine in one sense,
yet as we are none of us our own, let us be willing to serve Him whose we are,
and be obedient children unto Him who in love visited us.
Surely,
He it is who sees meet to separate us outwardly--yet I am often near to you in spirit.
I have had many satisfactory opportunities in this city,
and my friends seem to have unity with me, which is a strength to me.
I cannot forget what I have met with in my painful pilgrimage;
but have still hope that it hath been, and will be of service to me,
by making me more watchful and careful, for there is great need of watchfulness.

Many are ill,
and many die suddenly--how happy are all those who have made their peace with God!
I think I may say, I know that peace, and beg that I may be preserved to the end;
being assured,
that all those who are '`faithful unto death,`' shall receive '`a crown of life.`'

I was enabled to leave Bristol with a degree of satisfaction, on the 16th of fifth month,
accompanied by William Bragg and William Bush:--Robert
Peters also going to Hotwells to see his worthy wife,
who seems to be near her change, having fought a good fight,
and no doubt will finish her course with joy.
Mary Winter of Stourbridge, accompanied me into Wales.
We rode to New Passage, and with difficulty got safe over to the county of Monmouth.

Our first meeting was at Sheernewton, to which came several of the neighbours,
and we had a satisfactory opportunity.
We then proceeded to Pontypool, a poor place as to the situation of our professors;
but we had cause to be thankful to our Lord who sent us,
and was pleased to show unto us the states of the people,
with whom we had a meeting on the 18th. We then visited a few families in the town,
one of which, or rather the father thereof had done wickedly, but we knew it not,
yet were led to pay them a visit;
and soon after entering the house I had to believe that something was wrong;
after a time of silence I found an engagement to speak,
there being present two children of this person both grown up,
himself and his second wife.
At first the old man looked very stiff; but though an entire stranger,
I was led to speak very closely to his state and to mourn with the children,
desiring them not to bring forth the fruits of Sodom, nor the grapes of Gomorrah,
although their teeth had been set on edge by their parents;
neither to be worshippers of idols, nor in anyway to defile themselves; telling them,
that the Lord was of purer eyes than to behold iniquity with approbation,
neither should the sinner go unpunished.
Yet, although I was thus led, I had to speak of the beautiful situation of those,
who came through true repentance and amendment of
life to have their hearts purged from dead works,
and in them living sacrifices prepared,
and could offer them as upon God`'s holy mountain,
having access to the throne of divine grace, through Jesus Christ,
which I was desirous might be one day their situation,
therefore I exhorted them to beg for true repentance.
Surely it was a time of favour,
wherein the youth were encouraged and the old man brought down and broken into tears.
Oh! how often do we mourn,
because the fathers and mothers lead their poor children into captivity.

From Pontypool we had a long and tedious ride over the mountains to Irevirig;
lodged at John Bevan`'s the 19th of fifth month, and on the 23rd went to Nailth,
having meetings at both places.
Thence we went to Swansea, and attended meetings on first-day;
in the afternoon were at the funeral of a Friend named John Griffiths;
a great number of people attended, and a very solemn time it was.
We lodged at our friend Paul Bevan`'s, and on second-day,
with our dear friend Elizabeth Bevan visited several families,
being engaged to labour amongst them in spirit,
and in the demonstration and power of God to preach the Gospel;
for indeed the Gospel is the power of God, which is often preached in our souls;
and did all that hear it live in obedience unto it,
they would know redemption from sin and come to witness a being reconciled unto God,
his Spirit bearing witness with their spirits that they are his children.

On the 24th we proceeded to Carmarthen, and lodged at William Reynolds`'s,
where we had a meeting: thence to Haverfordwest to John Lewis`'s,
who went with us over a large and difficult ferry to Jamestown, where we had a meeting.
On first-day attended meetings at Haverfordwest,
and in the evening had an opportunity in the house
of a Friend at which several were present;
it was an exercising season,
but I was at length favoured with strength to speak in a very close manner, and to query,
whether the fathers and mothers, who once had been serviceable in the church of God,
were not now laying waste what they had helped to build!
It seemed to me to be so;
and that those who should have been the repairers
of breaches had broken down the wall of discipline,
and made way for the destruction of their children;
yet that the Lord had mercifully visited them with his servants,
and had hewn them by his prophets, but if they would not return and repent,
I believed the Lord would remove the stumbling blocks and pluck up the dead trees;
and in place thereof, raise up a people whom he would purify,
and that such should tread his courts, and only such could sing his praise.
By thus discharging my duty, although it was in fear, I obtained peace;
and our friend John Lewis concluded in supplication, confirming what had been said.
On the morrow we left for a place called Redstone, where we had a satisfactory meeting.
We then continued our journey to Carmarthen,
accompanied by William Reynolds and another Friend,
and had a meeting at a place called the New Inn to satisfaction,
although very close doctrine was preached.

We afterwards had a meeting at Pennibunt, on the 1st of sixth month;
on the 2nd had an evening meeting at Llandewey-Brevy
and lodged at the house where it was held,
but knew nothing of the people until afterward; for indeed, we do not inquire,
neither are we willing to be informed until our service is over;
but we think Friends should be careful where they take us.
We asked our guide soon after we entered the house,
if it would not have been better to take us to an inn;
for we were afraid that all was not well, but he said there was no place convenient;
so here we stayed, but had such a meeting as I hope I shall not forget.
Oh! how did the Lord lead me as into the secret places,
and engage my spirit in a deep and painful travail,
enabling me to tell unto the people their transgressions and to call upon them to repent,
for their sins seemed grievous.
And so they were, as I was afterwards informed;
for not only the people of the house had grievously erred,
but some of that meeting who had been preachers,
had been disowned for their wicked conduct, yet would at times preach to the people;
and these I was concerned to cry against.
We had hard labour in most places, finding very few that were rightly concerned,
yet these few were encouraged, and I hope, strengthened,
being made sensible that the Lord was with us of a truth,
and that "`with him is neither variableness nor shadow of turning.`"
Although many depart from him,
yet he remains a faithful Creator and a sure Helper in the needful time,
to all those who keep near him, and put their trust in him alone.

We next went to Talcord,
and Friends were informed that they might meet with us on first-day at this place;
several of them came, and we had a painful time of sitting together,
but were favoured in the conclusion and the meeting ended well.
On second-day we went to Esgyrgoch, in Montgomeryshire.
We had only one meeting in Cardiganshire, being all there is,
and held at Llandewey-Brevy; and we were but at one in Radnorshire,
as some from the other meetings met us at Talcord.
The few meetings in this principality are far distant from each other,
so that we had hard work to get from one place to another in one day.
We had a meeting at Esgyrgoch on third-day, which was dull and heavy.
On fourth-day we went to Llenynde, to Humphrey Owens`',
whose wife is the daughter of our worthy friend John Goodwin,
whom I have often heard called the "`Prince of Wales;`" we were glad of his company,
he and his wife both having lived to a good old age; and although thus advanced in years,
they are living members fresh and green.

We stayed here two nights and had a meeting,
in which I believe we should have been more favoured if all of us had been faithful;
I could not forbear thinking that something was wanting from our worthy friend;
yet said within myself, perhaps it is only because I should be glad to hear him;
but after meeting to my satisfaction and confirmation,
he told me that he was afraid of being in the way of strangers.
"`O!`" said I unto him, "`what a pity it was, that thou, who art a father,
should withhold any thing from a poor child, who was in such need of a little help.`"
He said, he always used to be fearful and backward.
However, he was open and free in conversation,
and told us many things which had befallen him in his pilgrimage,
and how wonderfully the Lord had made way for him, and been with him all along,
even unto this day.
Although at one time he had not where to lay his head,
he now by the favour of Providence, enjoys plenty of the things of this life,
is freed from the cares of worldly business, and like a faithful steward,
is ready when his Lord may be pleased to call him.
Oh! saith my spirit, that I, who have known something of the same trials,
and have also known the arm of the Lord to be made bare for my help,
may also know a being kept in humility,
and in a true sense of the goodness of God and of my own nothingness, that so over all,
God may be glorified, who alone is worthy.

We parted in much love and proceeded to Tyddynygarrag, where we had a meeting, I believe,
to the satisfaction of the few who are alive.
The next day being very wet, we remained and stayed the meeting on first-day,
and were well satisfied therewith.
We afterwards had meetings at Dolobran and Salop;
and on the 26th of sixth month at Colebrookdale.
Many thereabouts profess with us, but we had an exceedingly hard meeting amongst them;
some however, expressed their satisfaction at our visit,
and we were glad to find a few who were living in the Truth: for indeed,
the world and the things of it do too much prevail amongst us.
On the 18th were at Dudley at James Payton`'s, he and his mother being at home,
whose company was very acceptable; thence forward to Birmingham,
where my dear husband met me, and on the 22nd of sixth month we got safe home.
I was out this journey fourteen weeks,
and was favoured with the company of Mary Winter through the principality of Wales.
I was near two weeks in Worcester, near five in Bristol, and four in Wales;
from all which places I returned home in peace.

In the fifth month, 1764,
finding drawings in my mind to attend the Yearly Meeting in Wales, held at Wrexham,
I was at a forenoon meeting at Uttoxeter; in the afternoon,
in company with Thomas Shipley and his sister Hannah, went to Newcastle,
and next day to Wrexham, where I met several Friends I had known before,
and we were glad to see each other.
We were favoured with the company of Samuel Fothergill and Catherine Payton;
the meetings were large, and I think conducted to satisfaction.
On the 11th, came with Thomas Shipley and his sister to Chester,
and with Samuel Lucas I went the same night to Congleton,
and in the morning to our worthy friends John and Joshua Toft`'s, at Haregate.
We attended a funeral at Leek in the afternoon, where, after a long time of silence,
our aged friend John Toft, appeared in a sound, plain and lively testimony,
greatly to my satisfaction.

On first-day his brother appeared also in a lively manner,
and a satisfactory meeting we had together,
besides several profitable opportunities in his family.
It was an agreeable visit to me,
as I am persuaded that I found them as lively in
the blessed Truth as they had been in years past,
and have a hope that they will be gathered in due season, as shocks of corn fully ripe.
I parted with these my dear friends on the 15th, and arrived at home the next day,
when I found my family well, which was a great favour.
